plugins {
    id 'com.android.application'
}

android {
    namespace 'mx.hachenatacion.app'
    compileSdk 36

    defaultConfig {
        applicationId 'mx.hachenatacion.app'
        minSdk 23
        targetSdk 35
        versionCode 1
        versionName '0.1.0-test'
    }
}

dependencies {
    implementation 'com.google.androidbrowserhelper:androidbrowserhelper:2.7.2'
}
