<?php

declare(strict_types=1);
require_once __DIR__.'/../bin/intensive-partial-payment-triggers.php';
require_once __DIR__.'/../config/reglas-acceso.php';
function part_ok(bool $ok,string $message):void{if(!$ok){fwrite(STDERR,"FAIL: {$message}\n");exit(1);}}
$host=getenv('DELIVERY_DB_HOST')?:'127.0.0.1';$port=(int)(getenv('DELIVERY_DB_PORT')?:3306);$user=getenv('DELIVERY_DB_USER')?:'root';$pass=getenv('DELIVERY_DB_PASS')?:'root';
$admin=new PDO("mysql:host={$host};port={$port};charset=utf8mb4",$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
$db='hache_partial_'.getmypid();$admin->exec("CREATE DATABASE `{$db}` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci");
try{$pdo=new PDO("mysql:host={$host};port={$port};dbname={$db};charset=utf8mb4",$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
$pdo->exec("CREATE TABLE cursos_intensivos(id CHAR(36) PRIMARY KEY,sede_id CHAR(36) NOT NULL,precio DECIMAL(10,2) NOT NULL,estado ENUM('PROGRAMADO','EN_CURSO','TERMINADO') NOT NULL,fecha_inicio DATE NOT NULL,fecha_fin DATE NOT NULL) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE curso_intensivo_alumnos(alumno_id CHAR(36) NOT NULL,curso_intensivo_id CHAR(36) NOT NULL,horario_id CHAR(36) NULL) ENGINE=InnoDB");
$pdo->exec("CREATE TABLE pagos(id CHAR(36) PRIMARY KEY,alumno_id CHAR(36) NOT NULL,inscripcion_id CHAR(36) NULL,mensualidad_id CHAR(36) NULL,intensivo_id CHAR(36) NULL,tipo ENUM('INSCRIPCION','MENSUALIDAD','INTENSIVO') NOT NULL,importe DECIMAL(10,2) NOT NULL,estado ENUM('VALIDO','INVALIDO') NOT NULL DEFAULT 'VALIDO') ENGINE=InnoDB");
$pdo->prepare("INSERT INTO cursos_intensivos(id,sede_id,precio,estado,fecha_inicio,fecha_fin) VALUES('course-1','sede-1',1200.00,'PROGRAMADO','2026-09-01','2026-09-30')")->execute();$pdo->exec("INSERT INTO curso_intensivo_alumnos(alumno_id,curso_intensivo_id,horario_id) VALUES('student-1','course-1','horario-1')");hache_intensive_partial_payment_apply($pdo);part_ok(hache_intensive_partial_payment_triggers_ready($pdo),'Los triggers nuevos deben quedar verificables');
$insert=$pdo->prepare("INSERT INTO pagos(id,alumno_id,intensivo_id,tipo,importe,estado) VALUES(:id,'student-1','course-1','INTENSIVO',:importe,'VALIDO')");$insert->execute([':id'=>'p1',':importe'=>'600.00']);part_ok(!regla_intensivo_pagado($pdo,'student-1','sede-1','course-1'),'Un anticipo de 600 no debe otorgar acceso a un curso de 1200');$insert->execute([':id'=>'p2',':importe'=>'600.00']);part_ok(regla_intensivo_pagado($pdo,'student-1','sede-1','course-1'),'El acceso debe habilitarse al liquidar los 1200');$sum=(float)$pdo->query("SELECT SUM(importe) FROM pagos WHERE alumno_id='student-1' AND intensivo_id='course-1' AND estado='VALIDO'")->fetchColumn();part_ok(abs($sum-1200.0)<0.009,'Dos abonos de 600 deben liquidar un curso de 1200');
$blocked=false;try{$insert->execute([':id'=>'p3',':importe'=>'1.00']);}catch(PDOException $e){$blocked=str_contains($e->getMessage(),'El abono supera el saldo pendiente del intensivo');}part_ok($blocked,'Un tercer abono que exceda el precio debe bloquearse');
$pdo->exec("INSERT INTO pagos(id,alumno_id,mensualidad_id,tipo,importe,estado) VALUES('m1','student-1','monthly-1','MENSUALIDAD',1000,'VALIDO')");$monthlyBlocked=false;try{$pdo->exec("INSERT INTO pagos(id,alumno_id,mensualidad_id,tipo,importe,estado) VALUES('m2','student-1','monthly-1','MENSUALIDAD',1,'VALIDO')");}catch(PDOException $e){$monthlyBlocked=true;}part_ok($monthlyBlocked,'La unicidad de mensualidad debe permanecer intacta');
$updateBlocked=false;try{$pdo->exec("UPDATE pagos SET importe=700 WHERE id='p2'");}catch(PDOException $e){$updateBlocked=str_contains($e->getMessage(),'El abono supera el saldo pendiente del intensivo');}part_ok($updateBlocked,'Editar un abono tampoco puede exceder el precio del curso');
$sql=file_get_contents(__DIR__.'/../database/migrations/20260909_intensive_partial_payments.sql')?:'';part_ok(str_contains($sql,'SUM(p.importe)')&&str_contains($sql,'El abono supera el saldo pendiente del intensivo'),'La migración SQL debe documentar la misma protección');fwrite(STDOUT,"INTENSIVE_PARTIAL_PAYMENTS_MARIADB_OK\n");
}finally{$admin->exec("DROP DATABASE IF EXISTS `{$db}`");}
