<?php
declare(strict_types=1);
require_once __DIR__.'/../config/salad-monitor.php';
function expect(bool $ok,string $message): void {if(!$ok)throw new RuntimeException($message);}
$sample=[['time'=>'2026-10-07T18:00:00Z','text_log'=>"\e[32m#0 RTX 4070 Ti SUPER 161.58 TH/s 284.8W 0.567 73% 69C\e[0m"],['time'=>'2026-10-07T17:59:00Z','text_log'=>'15 min 161.64 TH/s'],['time'=>'2026-10-07T17:58:00Z','text_log'=>'Shares accepted 16 rejected 0 HW errors 0']];
$m=hache_salad_monitor_parse($sample);expect($m['gpu']==='RTX 4070 Ti SUPER','GPU no extraída');expect($m['hashrate_ths']===161.58,'TH/s actual no extraído');expect($m['hashrate_15m_ths']===161.64,'TH/s 15 min no extraído');expect($m['watts']===284.8&&$m['temperature_c']===69&&$m['fan_percent']===73,'Métricas de GPU no extraídas');expect($m['shares']['accepted']===16,'Shares no extraídas');expect(hache_salad_monitor_status('running',$m)==='green','Estado sano incorrecto');expect(hache_salad_monitor_status('running',$m,[['state'=>'running','ready'=>true,'started'=>true]])==='green','Instancia sana marcada incorrectamente');expect(hache_salad_monitor_status('running',$m,[['state'=>'running','ready'=>false,'started'=>true]])==='red','Instancia no ready debe ser roja');$m['temperature_c']=84;expect(hache_salad_monitor_status('running',$m)==='yellow','Estado térmico incorrecto');expect(hache_salad_monitor_status('deploying',$m)==='red','Estado de grupo incorrecto');
$yellow=['group'=>'simulation-4070','health'=>'yellow','stale'=>false,'state'=>'running','instances'=>[['state'=>'running','ready'=>true,'started'=>true]],'metrics'=>$m];$notifications=0;$notify=static function(array $group)use(&$notifications):bool{$notifications++;return true;};$first=hache_salad_monitor_apply_alert_transitions([$yellow],[],$notify);expect($first['sent']===1&&$notifications===1,'La primera entrada en amarillo debe alertar');$second=hache_salad_monitor_apply_alert_transitions([$yellow],$first['state'],$notify);expect($second['sent']===0&&$notifications===1,'No debe duplicar alerta mientras siga amarillo');$red=$yellow;$red['health']='red';$red['instances']=[['state'=>'stopped','ready'=>false,'started'=>false]];$escalated=hache_salad_monitor_apply_alert_transitions([$red],$second['state'],$notify);expect($escalated['sent']===1&&$notifications===2,'La transición de amarillo a rojo debe alertar');$sameRed=hache_salad_monitor_apply_alert_transitions([$red],$escalated['state'],$notify);expect($sameRed['sent']===0&&$notifications===2,'No debe duplicar alerta mientras siga rojo');$staleRed=$red;$staleRed['stale']=true;$staleFromGreen=hache_salad_monitor_apply_alert_transitions([$staleRed],['simulation-4070'=>['health'=>'green']],$notify);expect($staleFromGreen['sent']===0&&$notifications===2,'Un fallback stale no debe generar alerta roja');$green=$yellow;$green['health']='green';$recovered=hache_salad_monitor_apply_alert_transitions([$green],$sameRed['state'],$notify);expect($recovered['sent']===0&&$notifications===2,'La recuperación no debe alertar');$again=hache_salad_monitor_apply_alert_transitions([$yellow],$recovered['state'],$notify);expect($again['sent']===1&&$notifications===3,'Debe alertar de nuevo al volver a amarillo');

$lowGroup=['group'=>'low-4070','display_name'=>'Low 4070','state'=>'running','stale'=>false,'instances'=>[['id'=>'instance-a','state'=>'running','ready'=>true,'started'=>true]],'metrics'=>['gpu'=>'RTX 4070 Ti SUPER','hashrate_ths'=>165.0,'hashrate_15m_ths'=>164.0,'watts'=>280.0,'temperature_c'=>68,'fan_percent'=>55,'shares'=>['accepted'=>1,'rejected'=>0,'hardware_errors'=>0]]];
$reallocations=0;$reallocate=static function(array $group)use(&$reallocations):bool{$reallocations++;return true;};$reallocationNotices=0;$reallocNotify=static function(array $group,float $hash,int $seconds)use(&$reallocationNotices):bool{$reallocationNotices++;return true;};
$armed=hache_salad_monitor_apply_low_hash_reallocations([$lowGroup],[],$reallocate,$reallocNotify,1000);expect(($armed['state']['low-4070']['hash_baseline_seen']??false)===true,'Debe armarse tras observar hash sano');expect($armed['reallocated']===0,'No debe reasignar con hash sano');
$lowGroup['metrics']['hashrate_ths']=125.0;$firstLow=hache_salad_monitor_apply_low_hash_reallocations([$lowGroup],$armed['state'],$reallocate,$reallocNotify,1100);expect($firstLow['reallocated']===0&&($firstLow['state']['low-4070']['low_hash_since']??null)===1100,'Primera lectura baja debe iniciar temporizador');
$tooSoon=hache_salad_monitor_apply_low_hash_reallocations([$lowGroup],$firstLow['state'],$reallocate,$reallocNotify,1399);expect($tooSoon['reallocated']===0&&$reallocations===0,'No debe reasignar antes de cinco minutos');
$triggered=hache_salad_monitor_apply_low_hash_reallocations([$lowGroup],$tooSoon['state'],$reallocate,$reallocNotify,1400);expect($triggered['reallocated']===1&&$reallocations===1&&$reallocationNotices===1,'Debe reasignar al cumplir cinco minutos bajo 130 TH/s');expect(($triggered['state']['low-4070']['reallocation_requested_instance_id']??'')==='instance-a','Debe recordar la instancia ya reasignada');
$duplicate=hache_salad_monitor_apply_low_hash_reallocations([$lowGroup],$triggered['state'],$reallocate,$reallocNotify,1800);expect($duplicate['reallocated']===0&&$reallocations===1,'No debe reasignar dos veces la misma instancia');
$newNode=$lowGroup;$newNode['instances'][0]['id']='instance-b';$newNode['metrics']['hashrate_ths']=160.0;$recoveredHash=hache_salad_monitor_apply_low_hash_reallocations([$newNode],$duplicate['state'],$reallocate,$reallocNotify,1810);expect(array_key_exists('reallocation_requested_instance_id',$recoveredHash['state']['low-4070'])&&$recoveredHash['state']['low-4070']['reallocation_requested_instance_id']===null,'Nodo nuevo sano debe limpiar la marca anterior');
$newNode['metrics']['hashrate_ths']=120.0;$newLow=hache_salad_monitor_apply_low_hash_reallocations([$newNode],$recoveredHash['state'],$reallocate,$reallocNotify,1900);$newTrigger=hache_salad_monitor_apply_low_hash_reallocations([$newNode],$newLow['state'],$reallocate,$reallocNotify,2200);expect($newTrigger['reallocated']===1&&$reallocations===2,'Una instancia nueva también debe poder reasignarse tras cinco minutos bajos');
$stale=$newNode;$stale['stale']=true;$staleLow=hache_salad_monitor_apply_low_hash_reallocations([$stale],$newTrigger['state'],$reallocate,$reallocNotify,2600);expect($staleLow['reallocated']===0&&$reallocations===2,'Datos stale nunca deben provocar auto-reallocate');

$tmp=sys_get_temp_dir().'/hache-salad-monitor-'.bin2hex(random_bytes(6)).'.json';putenv('SALAD_MONITOR_SNAPSHOT_FILE='.$tmp);
$snapshotGroups=[['group'=>'g1','display_name'=>'G1','state'=>'running','instances'=>[],'metrics'=>['gpu'=>'RTX 4070 Ti SUPER','hashrate_ths'=>167.0,'shares'=>['accepted'=>3,'rejected'=>0,'hardware_errors'=>0]],'health'=>'green','stale'=>false,'observed_at'=>gmdate(DATE_ATOM)]];
hache_salad_monitor_write_snapshot($snapshotGroups);$snapshot=hache_salad_monitor_read_snapshot();expect($snapshot!==null,'Snapshot no leído');expect(($snapshot['groups'][0]['group']??'')==='g1','Snapshot perdió grupos');$age=hache_salad_monitor_snapshot_age_seconds((string)$snapshot['observed_at']);expect($age!==null&&$age<5,'Edad del snapshot incorrecta');@unlink($tmp);putenv('SALAD_MONITOR_SNAPSHOT_FILE');
echo "SALAD_MONITOR_REGRESSION_OK\n";
