<?php

declare(strict_types=1);

require_once __DIR__.'/../config/sharky-commercial-memory.php';
require_once __DIR__.'/../config/sharky-schedule-scope-guard.php';
require_once __DIR__.'/../config/sharky-product-boundary-guard.php';

function field_context_ok(bool $condition,string $message): void
{
    if(!$condition){fwrite(STDERR,"SHARKY FIELD CONTEXT FAIL: {$message}\n");exit(1);}
}

function field_context_state(array $commercial=[],?array $flow=null): array
{
    $state=hache_sharky_orchestrator_state(null,1789093000);
    $state['identity']=array_replace($state['identity'],[
        'kind'=>'prospect','verified'=>false,'source'=>'whatsapp_unmatched',
    ]);
    $state['commercial_context']=array_replace($state['commercial_context']??[],$commercial);
    $state['flow']=$flow;
    return $state;
}

// The short reply observed in production must resolve the pending training-history
// question even when Brain already preserved intensive as the active product.
$background=field_context_state(
    ['swim_level'=>'swims','program'=>'intensive'],
    ['name'=>'qualify_prospect','step'=>'background','data'=>[],'updated_at'=>1789093000]
);
$background=hache_sharky_commercial_reconcile_guidance($background,'No');
field_context_ok(($background['commercial_context']['background']??null)==='no_formal','Bare No must persist no_formal on the background cursor.');
field_context_ok(($background['commercial_context']['program']??null)==='intensive','No formal training must keep intensive canonical.');
field_context_ok(($background['flow']['step']??null)==='sede','Bare No must advance to venue instead of looping on background.');

// Natural venue references must update durable structured context, not merely the
// prose generated by Brain. Changing venue invalidates selections scoped to the old venue.
foreach([
    'Monteverde me gusta.'=>'MONTEVERDE',
    'Y en Palapas.'=>'PALAPAS',
    'Quiero ver los de Palapas.'=>'PALAPAS',
] as $text=>$expected){
    field_context_ok(hache_sharky_commercial_venue_browse_choice($text)===$expected,'Natural venue phrase must resolve: '.$text);
}
field_context_ok(hache_sharky_commercial_venue_browse_choice('¿Qué diferencia hay entre Monteverde y Palapas?')===null,'A two-venue comparison must not silently select one venue.');

$mvCatalog=[
    '_sede'=>'MONTEVERDE','_program'=>'intensive','plans'=>[],
    'schedules'=>[
        ['id'=>'mv8','label'=>'08:00–09:00'],
        ['id'=>'mv19','label'=>'19:00–20:00'],
        ['id'=>'mv20','label'=>'20:00–21:00'],
    ],
    'courses'=>[],
];
$venueState=field_context_state([
    'program'=>'intensive','sede_clave'=>'MONTEVERDE','swim_level'=>'swims','background'=>'no_formal',
    'schedule_id'=>'mv8','schedule_label'=>'08:00–09:00','course_id'=>'mv-course','fecha_inicio'=>'2026-09-14','course_price'=>1200,
]);
$venueState=hache_sharky_commercial_capture($venueState,'Quiero ver los de Palapas.',$mvCatalog,'2026-09-11');
field_context_ok(($venueState['commercial_context']['sede_clave']??null)==='PALAPAS','Palapas browse must update durable venue.');
field_context_ok(!isset($venueState['commercial_context']['schedule_id'])&&!isset($venueState['commercial_context']['course_id']),'Venue change must invalidate stale schedule/course ids.');
field_context_ok(($venueState['commercial_context']['program']??null)==='intensive','Venue change must preserve the active product.');

$stale=hache_sharky_commercial_reply($venueState,'En Palapas te muestro los horarios.',$mvCatalog);
field_context_ok(($stale['kind']??'')==='commercial_scope_refreshed','A catalog loaded for the previous venue must be detected as stale.');
field_context_ok(empty($stale['ui']??[]),'Stale Monteverde controls must never be sent after state changes to Palapas.');

$palCatalog=[
    '_sede'=>'PALAPAS','_program'=>'intensive','plans'=>[],
    'schedules'=>[
        ['id'=>'pal7','label'=>'07:00–08:00'],
        ['id'=>'pal8','label'=>'08:00–09:00'],
        ['id'=>'pal9','label'=>'09:00–10:00'],
        ['id'=>'pal20','label'=>'20:00–21:00'],
    ],
    'courses'=>[],
];
$palMorning=hache_sharky_commercial_reply($venueState,'Horarios de la mañana en Palapas Protudec.',$palCatalog);
$palButtons=$palMorning['ui']['buttons']??[];$palOptions=$palMorning['ui']['options']??[];
$palTitles=array_column($palButtons?:$palOptions,'title');
field_context_ok($palTitles===['07:00–08:00','08:00–09:00','09:00–10:00'],'Palapas morning controls must be rebuilt from the Palapas intensive catalog only.');
field_context_ok(!in_array('20:00–21:00',$palTitles,true),'Morning controls must omit the Palapas night slot.');

// The schedule firewall owns a bare daypart follow-up even when the user does not
// repeat the words horario/horarios.
$loader=static function(string $program,string $sede): array {
    if($program!=='intensive')return [];
    return $sede==='MONTEVERDE'
        ?['08:00–09:00','19:00–20:00','20:00–21:00']
        :['07:00–08:00','08:00–09:00','09:00–10:00','20:00–21:00'];
};
$mvState=field_context_state(['program'=>'intensive','sede_clave'=>'MONTEVERDE','swim_level'=>'swims','background'=>'no_formal']);
$morning=hache_sharky_schedule_guard_scoped_reply('En la mañana',$mvState,$loader)??'';
field_context_ok(str_contains($morning,'08:00–09:00'),'Monteverde intensive morning must include 08:00–09:00.');
field_context_ok(!str_contains($morning,'06:00–07:00')&&!str_contains($morning,'07:00–08:00'),'Monteverde regular-only morning slots must never leak into intensive.');
field_context_ok(!str_contains($morning,'19:00–20:00')&&!str_contains($morning,'20:00–21:00'),'Bare morning scope must filter evening intensive slots.');
$repaired=hache_sharky_schedule_guard_model_answer(
    'Los horarios de la mañana son 06:00–07:00, 07:00–08:00 y 08:00–09:00.',
    $mvState,
    'En la mañana',
    $loader
);
field_context_ok(str_contains($repaired,'08:00–09:00')&&!str_contains($repaired,'06:00–07:00')&&!str_contains($repaired,'07:00–08:00'),'Final schedule firewall must repair a wrong bare-daypart answer.');

// Exact new-ad failure: an accidental model mention of regular classes must not
// manufacture a regular-sales question when the user only asked for information
// from an intensive ad.
$adState=field_context_state(['entry_source'=>'meta_ad','entry_interest'=>'intensive']);
$modelLeak='En Hache Natación tenemos curso intensivo y también clases regulares para quien ya nada.';
$adGuard=hache_sharky_product_boundary_model_answer($modelLeak,$adState,'¡Hola! Quiero más información');
$adNorm=hache_sharky_product_boundary_normalize($adGuard);
field_context_ok(str_contains($adNorm,'ya sabes nadar')||str_contains($adNorm,'empezando desde cero'),'Intensive-ad model leak must recover to level discovery.');
field_context_ok(!str_contains($adNorm,'antes de ofrecerte clases regulares'),'User did not ask for regular classes; the guard must not invent that intent.');

$restricted=field_context_state([
    'program'=>'intensive','entry_interest'=>'intensive','swim_level'=>'swims','background'=>'no_formal','sede_clave'=>'MONTEVERDE',
]);
$genericGuard=hache_sharky_product_boundary_model_answer('Tenemos clases regulares de 3 o 5 veces por semana.',$restricted,'Precio de las clases');
field_context_ok(!str_contains(hache_sharky_product_boundary_normalize($genericGuard),'persona del equipo'),'A generic active-product question must not be treated as a request for a regular exception.');
$explicitGuard=hache_sharky_product_boundary_model_answer('Tenemos clases regulares.',$restricted,'Prefiero clases regulares');
field_context_ok(str_contains(hache_sharky_product_boundary_normalize($explicitGuard),'persona del equipo'),'An explicit restricted request for regular classes must still require a human exception.');

fwrite(STDOUT,"SHARKY_FIELD_CONTEXT_OK\n");
