<?php
declare(strict_types=1);
require __DIR__.'/../config/sharky-runtime.php';

$mustHandoff = [
    'Quiero hablar con una persona',
    'Necesito un asesor',
    '¿Me puedes pasar con alguien del equipo?',
    'Quisiera comunicarme con un humano',
    '¿Hay cupo para el intensivo?',
    '¿Hay cupo a las ocho?',
    '¿Hay cupo en los cursos a las ocho?',
    '¿Cuántos alumnos hay por carril?',
    '¿Cuántos alumnos hay por grupo?',
    'En los grupos, ¿cuántos alumnos hay?',
    '¿Cuántos caben en el grupo?',
    '¿Cuántos admite el curso?',
    '¿Cuántos entran en cada carril?',
    'En el grupo, ¿cuántos caben?',
    '¿Cuántos caben en el grupo el lunes?',
    '¿Cuántos entran en cada carril a las ocho?',
    '¿Cuántos lugares hay en el curso?',
    '¿Cuántos espacios quedan en el grupo?',
    'En el intensivo, ¿cuántos lugares hay?',
    '¿Qué cantidad de espacios hay para las clases?',
    '¿Cuántos lugares quedan?',
    '¿Número de espacios disponibles en el grupo?',
    '¿Cuántos lugares hay en el curso el lunes?',
    '¿Cuántos espacios quedan en el grupo a las ocho?',
    '¿Cuál es la capacidad del grupo?',
    '¿Qué capacidad tiene el grupo?',
    '¿Cuál es la capacidad máxima del intensivo?',
    '¿Tienen lugares disponibles en el curso?',
    '¿Hay disponibilidad para el intensivo?',
    '¿El grupo tiene disponibilidad?',
    '¿Hay disponibilidad en los cursos?',
    '¿Qué grupos tienen disponibilidad?',
    '¿Hay disponibilidad en los intensivos?',
    '¿Las clases tienen disponibilidad?',
    '¿Hay disponibilidad en el carril?',
    '¿Qué carriles tienen disponibilidad?',
    '¿Hay disponibilidad en los carriles?',
    '¿Tienen disponibilidad de cupo en el horario de las 8?',
    '¿Hay disponibilidad de horarios y cuántos alumnos hay por carril?',
    '¿Quedan lugares?',
    '¿Quedan lugares en el grupo el 7 de septiembre?',
    '¿Hay espacio en los cursos el lunes?',
    '¿Cuántas personas admite el grupo?',
    'En el curso, ¿cuántos alumnos hay?',
    '¿Cuánta gente hay en el grupo?',
    '¿Qué cantidad de gente entra en el curso?',
    '¿Cuánta gente cabe por carril?',
    '¿Cuál es el aforo del grupo?',
    '¿Hay vacantes?',
    '¿Está lleno el grupo?',
    '¿El grupo ya se llenó?',
    '¿Ya se llenó el curso?',
    '¿Se llenaron los grupos?',
    '¿Hay espacio en el curso del lunes?',
    '¿Está disponible el intensivo de septiembre?',
    '¿Tienen lista de espera?',
    'Quiero inscribirme a clases regulares',
    '¿Cómo me registro en regular?',
    'Quiero darme de alta en mensualidad',
    'Ya quiero empezar con las clases regulares',
    'Quiero inscribir a mi hijo a clases regulares',
    '¿Puedo registrar a mi esposa en regular?',
    'Necesito anotar a mi hija en clases regulares',
    'Para clases regulares quiero inscribir a mi esposo',
    '¿Cómo puedo dar de alta a mi mamá en mensualidad?',
    'Voy a inscribirlo a regular',
    'Mi esposa quiere inscribirse a clases regulares',
    'Mi hijo desea registrarse en regular',
    'Ella quiere darse de alta en mensualidad',
    'Mis hijos quieren anotarse a clases regulares',
    '¿Cómo puede registrarse mi esposa a clases regulares?',
    'No quiero información, quiero inscribirme a clases regulares',
    'No necesito información, quiero registrar a mi hijo en regular',
    'No quiero inscribirme a regular, quiero hablar con una persona',
    'No quiero inscribirme yo; quiero inscribir a mi hijo en clases regulares',
    'No quiero inscribirme yo quiero inscribir a mi hijo en clases regulares',
    'Yo no quiero registrarme, pero mi esposa quiere inscribirse a clases regulares',
    'No quiero inscribirme yo; sin embargo necesito registrar a mi hija en regular',
    'Mi esposa no se quiere inscribir; yo quiero registrarme a clases regulares',
    'Mis hijos no se van a inscribir, pero yo quiero inscribirme a regular',
    'Quiero hacer la inscripción a clases regulares',
    'Necesito la inscripción de clases regulares',
    'Quiero confirmar mi alta regular',
    'Quiero realizar mi registro para clases regulares',
    'Para clases regulares quiero completar la inscripción',
    'Quiero inscripción regular',
];
$mustStayWithSharky = [
    'Quiero hablar de precios',
    'Necesito información del curso intensivo',
    '¿Puedo hablar de los horarios?',
    'Quiero saber si tienen goggles',
    '¿Qué horarios están disponibles?',
    '¿Qué fechas tienen disponibles?',
    '¿Tienen disponibilidad de horarios?',
    '¿Hay disponibilidad de fechas para septiembre?',
    '¿Hay disponibilidad para el horario de las 8?',
    '¿Hay disponibilidad en el horario de las 8?',
    '¿Hay disponibilidad por la mañana?',
    '¿Hay disponibilidad por la tarde?',
    '¿Hay disponibilidad en la noche?',
    '¿Hay disponibilidad a las 8?',
    '¿Hay disponibilidad para las 8:00?',
    '¿Hay disponibilidad a las ocho?',
    '¿Hay disponibilidad a las ocho y media?',
    '¿Tienen disponibilidad a las siete de la mañana?',
    '¿Hay disponibilidad para el intensivo a las nueve?',
    '¿Hay disponibilidad para el intensivo en el horario de las 8?',
    '¿Hay disponibilidad en los cursos a las ocho?',
    '¿Qué grupos tienen disponibilidad a las ocho?',
    '¿Hay disponibilidad en el carril a las ocho?',
    '¿Hay disponibilidad en los cursos el lunes?',
    '¿Hay disponibilidad para clases los lunes?',
    '¿Qué grupos tienen disponibilidad el 7 de septiembre?',
    '¿Qué grupos tienen disponibilidad en septiembre?',
    '¿Hay disponibilidad en las clases el martes?',
    '¿Hay disponibilidad en el curso el 07/09/2026?',
    '¿Hay disponibilidad en los cursos de 7 a 8?',
    '¿Qué grupos tienen disponibilidad entre siete y ocho?',
    '¿Hay disponibilidad en los cursos a las 8 pm?',
    '¿En qué lugar hay disponibilidad en los cursos el lunes?',
    '¿Cuántos lugares tiene Hache en Cancún?',
    '¿Qué lugares hay cerca de Monteverde?',
    '¿Cuántos espacios de estacionamiento hay en Monteverde?',
    '¿Hay lugar para estacionarse en Monteverde?',
    '¿Hay disponibilidad en la mañana para el intensivo?',
    '¿Tienen disponibilidad de horario por la noche?',
    '¿Tienen disponibilidad de horarios para una persona?',
    '¿Hay disponibilidad de fechas para alumnos nuevos?',
    '¿Está disponible el horario de las 8?',
    '¿Hay horarios disponibles en Monteverde?',
    '¿Cuáles son las fechas disponibles del intensivo?',
    '¿Qué días están disponibles para empezar?',
    '¿Hay disponibilidad?',
    '¿Tienen disponibilidad?',
    'Quiero inscribirme al intensivo',
    '¿Cómo me registro al intensivo?',
    'Quiero inscribir a mi hijo al intensivo',
    '¿Puedo registrar a mi esposa en el intensivo?',
    'Mi esposa quiere inscribirse al intensivo',
    'Mi hijo desea registrarse al intensivo',
    'Quiero información de clases regulares',
    '¿Cuánto cuestan las clases regulares?',
    '¿Qué horarios hay de regular?',
    'No quiero inscribirme a clases regulares, solo quiero información',
    'Todavía no necesito registrarme en regular',
    'Aún no quiero anotarme a clases regulares',
    'Por ahora no quiero darme de alta en mensualidad',
    'No me quiero inscribir a regular todavía',
    'No quiero registrar a mi hijo en clases regulares, solo quiero información',
    'Todavía no quiero inscribir a mi esposa en regular',
    'No quiero inscribirme yo ni registrar a mi hijo en clases regulares',
    'Mi esposa tampoco quiere inscribirse a regular',
    'Mi esposa no se quiere inscribir a clases regulares',
    'Mi hijo no se va a registrar en regular',
    'Ellos no se quieren anotar a clases regulares',
    'Nosotros no nos queremos inscribir a regular',
    'Mi esposa no se quiere dar de alta en mensualidad',
    'No tengo intención de inscribirme a clases regulares',
    'No tienen planes de registrarse en regular',
    'No quiero empezar las clases regulares todavía',
    'No necesito la inscripción de clases regulares',
    'No quiero confirmar mi alta regular',
    'Quiero información sobre la inscripción de clases regulares',
    'Quiero información sobre el alta regular',
    '¿Dónde queda Monteverde?',
    '¿Necesito cierta capacidad física para entrar al curso?',
    '¿Qué capacidad física necesito para aprender a nadar?',
    'Quiero mejorar mi capacidad pulmonar nadando',
    '¿Se necesita alguna capacidad de aprendizaje especial?',
    '¿Hay gente de mi edad en el grupo?',
    '¿Va gente que ya sabe nadar?',
];

foreach ($mustHandoff as $text) {
    if (!hache_sharky_human_request($text)) {
        fwrite(STDERR, "No detectó handoff: {$text}\n");
        exit(1);
    }
}
foreach ($mustStayWithSharky as $text) {
    if (hache_sharky_human_request($text)) {
        fwrite(STDERR, "Falso positivo de handoff: {$text}\n");
        exit(1);
    }
}

echo "Sharky handoff intent regression: OK\n";