<?php

declare(strict_types=1);

require_once __DIR__.'/../config/sharky-lab-worker.php';

function pr162_review_ok(bool $ok,string $message): void
{
    if(!$ok){fwrite(STDERR,"SHARKY PR162 REVIEW FAIL: $message\n");exit(1);}
}

$now=1788883200;
$pdo=new PDO('sqlite::memory:');

$fresh=hache_sharky_orchestrator_state(null,$now);
$fresh['identity']=array_replace($fresh['identity'],[
    'kind'=>'prospect','verified'=>false,'source'=>'whatsapp_unmatched',
]);

// WhatsApp directo now uses the same closed Sharky 3.0 selector as Meta.
$firstText="Quiero clases regulares\nMonteverde";
$guided=hache_sharky_entry_guided_first_prospect($fresh,$firstText,$now);
pr162_review_ok(($guided['commercial_context']['entry_source']??null)==='direct','Fresh unmatched WhatsApp must keep direct source attribution.');
pr162_review_ok(($guided['commercial_context']['entry_interest']??null)==='regular','Direct entry interest must remain durable discovery context.');
pr162_review_ok(($guided['flow']['name']??null)===HACHE_SHARKY_META_FLOW&&($guided['flow']['step']??null)==='program','Fresh direct prospects must start at the closed product selector.');
pr162_review_ok(($guided['flow']['data']['entry_bootstrap']??false)===true,'First-turn closed onboarding must be marked as entry bootstrap.');
pr162_review_ok(empty($guided['commercial_context']['program']),'Direct entry wording must not preselect a canonical program.');
pr162_review_ok(empty($guided['commercial_context']['sede_clave']),'Direct entry wording must not preselect a venue.');
pr162_review_ok(hache_sharky_entry_intro($guided,$firstText)==='Hola, soy Sharky 🦈, asistente IA de Hache Natación.','Direct closed onboarding must use the deterministic AI greeting.');

$handled=hache_sharky_meta_handle($pdo,$guided,[
    'from'=>'529981112233','text'=>$firstText,'interactive_id'=>'',
],$now+1,['contact'=>'529981112233']);
pr162_review_ok(is_array($handled),'Direct Sharky 3.0 bootstrap must produce a deterministic response.');
[$directWelcome,$directDecision]=$handled;
pr162_review_ok(($directDecision['kind']??null)==='meta_program_prompt','Direct first turn must show the approved product selector.');
pr162_review_ok(array_column($directDecision['ui']['buttons']??[],'id')===['meta:program:learn','meta:program:regular'],'Direct first turn must expose only the two approved product buttons.');
pr162_review_ok(empty($directWelcome['commercial_context']['program']),'Direct text must not become product authority before a button tap.');

// Prefills generated by hnATACION.com retain web attribution but use the same selector.
$webText='Hola Hache Natación, quiero inscribirme al curso intensivo';
$webGuided=hache_sharky_entry_guided_first_prospect($fresh,$webText,$now);
pr162_review_ok(($webGuided['commercial_context']['entry_source']??null)==='web','Known website WhatsApp prefill must be classified as web.');
pr162_review_ok(($webGuided['commercial_context']['entry_interest']??null)==='intensive','Website product wording may remain attribution context.');
pr162_review_ok(($webGuided['flow']['name']??null)===HACHE_SHARKY_META_FLOW&&($webGuided['flow']['step']??null)==='program','Website prospect must enter the same closed selector.');
pr162_review_ok(empty($webGuided['commercial_context']['program']),'Website prefill must not preselect intensive.');

$webGeneric=hache_sharky_entry_guided_first_prospect($fresh,'Hola Hache Natación, quiero orientación para elegir programa y sede',$now);
pr162_review_ok(($webGeneric['commercial_context']['entry_source']??null)==='web','Generic website orientation prefill must still retain web source.');
pr162_review_ok(($webGeneric['commercial_context']['entry_interest']??null)===null,'Generic website orientation must not invent product interest.');
pr162_review_ok(($webGeneric['flow']['name']??null)===HACHE_SHARKY_META_FLOW,'Generic website prospect must still use the closed selector.');

// A non-ad referral remains on the legacy profile-first route for now.
$referralState=$fresh;
$referralState['referral']['latest']=[
    'source_type'=>'post','source_url'=>'https://example.com/referencia','headline'=>'Referencia orgánica',
];
$referralGuided=hache_sharky_entry_guided_first_prospect($referralState,'Hola',$now);
pr162_review_ok(($referralGuided['commercial_context']['entry_source']??null)==='referral','Non-ad referral must retain referral source.');
pr162_review_ok(($referralGuided['flow']['name']??null)==='prospect_onboarding'&&($referralGuided['flow']['step']??null)==='name','Non-ad referrals keep the legacy profile-first fallback.');

// Click-to-WhatsApp referral must be attached before entry context is derived.
$webhook=(string)file_get_contents(__DIR__.'/../public/api/whatsapp-orchestrator-lab.php');
$referralPos=strpos($webhook,'$referral=hache_sharky_orchestrator_referral($event,$now);');
$capturePos=strpos($webhook,'$state=hache_sharky_orchestrator_capture_referral($state,$referral);',$referralPos===false?0:$referralPos);
$bootstrapPos=strpos($webhook,'$state=hache_sharky_entry_guided_first_prospect($state,(string)($event[\'text\']??\'\'),$now);',$capturePos===false?0:$capturePos);
pr162_review_ok($referralPos!==false&&$capturePos!==false&&$bootstrapPos!==false&&$referralPos<$capturePos&&$capturePos<$bootstrapPos,'Webhook must capture referral into state before onboarding derives source/interest.');

// Meta Ads keep their attribution while sharing the same deterministic engine.
$metaEvent=[
    'referral'=>[
        'source_type'=>'ad','source_id'=>'1200000001','headline'=>'Intensivo septiembre',
        'body'=>'Aprende a nadar','ctwa_clid'=>'clid-pr162',
    ],
];
$metaState=$fresh;
$ref=hache_sharky_orchestrator_referral($metaEvent,$now);
pr162_review_ok(is_array($ref),'Meta referral fixture must normalize successfully.');
$metaState=hache_sharky_orchestrator_capture_referral($metaState,$ref);
$metaGuided=hache_sharky_entry_guided_first_prospect($metaState,'Hola',$now);
pr162_review_ok(($metaGuided['commercial_context']['entry_source']??null)==='meta_ad','First CTWA turn must retain Meta-ad source.');
pr162_review_ok(($metaGuided['commercial_context']['entry_interest']??null)==='intensive','Current Meta ad must retain intensive attribution.');
pr162_review_ok(empty($metaGuided['commercial_context']['program']),'Meta referral interest must not become canonical program by itself.');
pr162_review_ok(($metaGuided['flow']['name']??null)===HACHE_SHARKY_META_FLOW&&($metaGuided['flow']['step']??null)==='program','Meta Ads must enter the common Sharky 3.0 program selector.');
pr162_review_ok(hache_sharky_entry_intro($metaGuided,'Hola')==='Hola, soy Sharky 🦈, asistente IA de Hache Natación.','Meta 3.0 must restore its deterministic IA disclosure at the WhatsApp presentation boundary.');

$handled=hache_sharky_meta_handle($pdo,$metaGuided,['from'=>'529981112233','text'=>'Hola','interactive_id'=>''],$now+1,['contact'=>'529981112233']);
pr162_review_ok(is_array($handled),'Meta 3.0 bootstrap must produce a deterministic response.');
[$metaWelcome,$metaDecision]=$handled;
pr162_review_ok(($metaDecision['kind']??null)==='meta_program_prompt','Meta first turn must show the approved product selector.');
pr162_review_ok(str_contains((string)($metaDecision['message']??''),'Soy Sharky 🦈, el asistente IA de Hache Natación.'),'Meta first turn must clearly disclose Sharky as an IA assistant.');
pr162_review_ok(array_column($metaDecision['ui']['buttons']??[],'id')===['meta:program:learn','meta:program:regular'],'Meta first turn must expose only the two approved product buttons.');
pr162_review_ok(empty($metaWelcome['commercial_context']['program']),'An intensive campaign still must not preselect intensive before the user taps a product.');

$handled=hache_sharky_meta_handle($pdo,$metaWelcome,[
    'from'=>'529981112233','text'=>'Clases regulares','interactive_id'=>'meta:program:regular',
],$now+2,['contact'=>'529981112233']);
pr162_review_ok(is_array($handled),'Explicit regular selection must be handled by Sharky 3.0.');
[$metaRegular,$regularDecision]=$handled;
pr162_review_ok(($metaRegular['flow']['step']??null)==='regular_background','Regular selection must ask the previous-classes question before becoming canonical.');
pr162_review_ok(empty($metaRegular['commercial_context']['program']),'Campaign attribution must not bypass the regular eligibility check.');
pr162_review_ok(array_column($regularDecision['ui']['buttons']??[],'id')===['meta:regular:yes','meta:regular:no'],'Regular eligibility must retain both deterministic choices.');

// A course button that went stale must invalidate the old selected course and
// refresh the course controls; it must never expose enrollment for the old date.
$staleState=hache_sharky_orchestrator_state(null,$now);
$staleState['identity']=array_replace($staleState['identity'],['kind'=>'prospect','verified'=>false,'source'=>'whatsapp_unmatched']);
$staleState['commercial_context']=array_replace($staleState['commercial_context'],[
    'program'=>'intensive','sede_clave'=>'MONTEVERDE',
    'schedule_id'=>'h8','schedule_label'=>'08:00–09:00',
    'course_id'=>'old14','fecha_inicio'=>'2026-09-14','course_price'=>1200.0,
    '_requested_slot'=>'course',
]);
$currentCourses=[
    ['id'=>'c21','sede_clave'=>'MONTEVERDE','fecha_inicio'=>'2026-09-21','precio'=>1200,'schedules'=>[['id'=>'h8','label'=>'08:00–09:00']]],
    ['id'=>'c28','sede_clave'=>'MONTEVERDE','fecha_inicio'=>'2026-09-28','precio'=>1200,'schedules'=>[['id'=>'h8','label'=>'08:00–09:00']]],
];
$staleResult=hache_sharky_commercial_interactive_input($pdo,$staleState,[
    'text'=>'Lun 5 oct','interactive_id'=>'action:commercial:course:gone05',
],[
    'today'=>'2026-09-08','intensive_options'=>$currentCourses,'min_age'=>12,
]);
pr162_review_ok(is_array($staleResult),'Stale requested-course tap must receive a deterministic response.');
[$afterStale,$staleDecision]=$staleResult;
pr162_review_ok(empty($afterStale['commercial_context']['course_id'])&&empty($afterStale['commercial_context']['fecha_inicio']),'Stale requested-course tap must invalidate the previously selected course/date.');
pr162_review_ok(($afterStale['commercial_context']['_requested_slot']??null)==='course','Stale requested-course tap must remain on course selection until a current option succeeds.');
$staleIds=array_column($staleDecision['ui']['buttons']??[],'id');
pr162_review_ok($staleIds===['action:commercial:course:c21','action:commercial:course:c28'],'Stale course response must refresh only currently valid backend course buttons.');
pr162_review_ok(!in_array('action:register_intensive',$staleIds,true),'Stale course response must never offer enrollment for the old date.');

fwrite(STDOUT,"SHARKY_PR162_REVIEW_OK\n");