<?php
declare(strict_types=1);
require_once __DIR__ . '/../config/auth.php';
require_once __DIR__ . '/../config/intensivos-estado.php';
page_require(['ADMIN']);
$config = require __DIR__ . '/../config/database.php';
$pdo = new PDO("mysql:host={$config['host']};dbname={$config['dbname']};charset={$config['charset']}",$config['user'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$sedeActiva=auth_active_sede_clave();
$cursoPreset=trim((string)($_GET['curso_id']??''));
$horarios=$pdo->query("SELECT h.id,h.hora_inicio,h.hora_fin,s.clave sede_clave FROM horarios h INNER JOIN sedes s ON s.id=h.sede_id WHERE h.activo=1 AND h.regular=1 ORDER BY s.clave,h.hora_inicio")->fetchAll();
$planes=$pdo->query("SELECT p.id,p.nombre,p.sesiones_semana,p.precio,s.clave sede_clave FROM planes p INNER JOIN sedes s ON s.id=p.sede_id WHERE p.activo=1 ORDER BY s.clave,p.sesiones_semana")->fetchAll();
$lunesActual=intensivo_lunes_semana_actual()->format('Y-m-d');
$st=$pdo->prepare("SELECT ci.id,ci.fecha_inicio,ci.fecha_fin,ci.precio,ci.estado,s.clave sede_clave FROM cursos_intensivos ci INNER JOIN sedes s ON s.id=ci.sede_id WHERE s.activo=1 AND (ci.fecha_inicio>=:lunes OR ci.id=:preset) ORDER BY ci.fecha_inicio,s.clave");
$st->execute([':lunes'=>$lunesActual,':preset'=>$cursoPreset]);$cursos=$st->fetchAll();
foreach($cursos as &$curso){$curso['estado']=intensivo_estado_por_fechas((string)$curso['fecha_inicio'],(string)$curso['fecha_fin']);$curso['cierre_inscripcion']=intensivo_cierre_inscripcion((string)$curso['fecha_inicio']);$curso['historico']=!intensivo_inscripcion_abierta((string)$curso['fecha_inicio']);}unset($curso);
$horariosIntensivo=$pdo->query("SELECT h.id,h.hora_inicio,h.hora_fin,s.clave sede_clave FROM horarios h INNER JOIN sedes s ON s.id=h.sede_id WHERE h.activo=1 AND h.intensivo=1 ORDER BY s.clave,h.hora_inicio")->fetchAll();
function e(?string $v):string{return htmlspecialchars($v??'',ENT_QUOTES,'UTF-8');}
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Agregar alumno — Hache Natación</title>
<style>*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;background:#f4f7fb;color:#172033}.contenedor{width:min(760px,92%);margin:40px auto}.encabezado{margin-bottom:25px}.encabezado h1{margin:0 0 8px;font-size:30px}.encabezado p{margin:0;color:#667085}.card{background:#fff;border-radius:18px;padding:30px;box-shadow:0 8px 30px rgba(0,0,0,.08)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.campo{display:flex;flex-direction:column;gap:7px}.campo.completo{grid-column:1/-1}label{font-weight:600;font-size:14px}input,select,textarea{width:100%;padding:13px 14px;border:1px solid #d0d5dd;border-radius:10px;font-size:15px;background:#fff;outline:none}input[readonly]{background:#f8fafc;color:#475569}textarea{min-height:100px;resize:vertical}.ayuda{margin-top:2px;color:#667085;font-size:13px;line-height:1.4}.historico{padding:13px 14px;border-radius:10px;background:#fff8e8;border:1px solid #f1c45b;color:#72520d;font-size:13px;line-height:1.45}.oculto{display:none!important}.acciones{margin-top:25px;display:flex;justify-content:flex-end}button{border:0;border-radius:10px;padding:14px 24px;background:#2563eb;color:#fff;font-size:15px;font-weight:700;cursor:pointer}button:disabled{opacity:.6;cursor:wait}#mensaje{display:none;margin-bottom:20px;padding:14px;border-radius:10px;font-weight:600;line-height:1.45}.exito{display:block!important;background:#dcfce7;color:#166534}.error{display:block!important;background:#fee2e2;color:#991b1b}.cred{margin-top:10px;padding-top:10px;border-top:1px solid #bbf7d0;font-family:monospace;font-size:14px}@media(max-width:650px){.contenedor{width:100%;margin:0;padding:72px 14px 20px}.grid{grid-template-columns:1fr}.campo.completo{grid-column:auto}.card{padding:20px}.encabezado h1{font-size:25px}}</style></head><body>
<div class="contenedor"><div class="encabezado"><h1>Agregar alumno</h1><p id="subtituloAlta">El alumno quedará pendiente hasta registrar su primer pago válido.</p></div><div id="mensaje"></div><div class="card"><form id="formAlumno"><div class="grid">
<div class="campo completo"><label for="sede">Sede *</label><select id="sede" required><option value="MONTEVERDE" <?=$sedeActiva==='MONTEVERDE'?'selected':''?>>Monteverde</option><option value="PALAPAS" <?=$sedeActiva==='PALAPAS'?'selected':''?>>Palapas</option></select></div>
<div class="campo completo"><label for="tipo_ingreso">Tipo de ingreso *</label><select id="tipo_ingreso" required><option value="REGULAR">Alumno regular</option><option value="INTENSIVO">Curso intensivo</option></select><div class="ayuda" id="ayudaTipo"></div></div>
<div class="campo completo oculto" id="avisoHistorico"><div class="historico"><strong>Corrección histórica de ADMIN.</strong> Este curso ya cerró para nuevas inscripciones. Puedes crear al alumno porque estás completando información atrasada. Escribe en Observaciones el motivo real de la corrección; quedará auditado y no se enviará alerta de “nueva inscripción”.</div></div>
<div class="campo completo oculto" id="campoCiclo"><label for="ciclo_pago">Ciclo de pago Palapas *</label><select id="ciclo_pago"><option value="">Seleccionar...</option><option value="P1">P1 — renovación día 1</option><option value="P15">P15 — renovación día 15</option></select><div class="ayuda">La mensualidad sigue siendo mensual; solo cambia el día de renovación.</div></div>
<div class="campo completo oculto" id="campoCurso"><label for="curso_intensivo_id">Curso intensivo *</label><select id="curso_intensivo_id"><option value="">Seleccionar curso...</option><?php foreach($cursos as $c):?><option value="<?=e($c['id'])?>" data-sede="<?=e($c['sede_clave'])?>" data-inicio="<?=e($c['fecha_inicio'])?>" data-historico="<?=$c['historico']?'1':'0'?>"><?=e(date('d/m/Y',strtotime($c['fecha_inicio'])).' · '.$c['estado'].($c['historico']?' · CORRECCIÓN HISTÓRICA':' · inscripciones hasta '.date('d/m',strtotime($c['cierre_inscripcion']))))?></option><?php endforeach;?></select><div class="ayuda">Las altas normales conservan su ventana habitual. Un curso pasado solo aparece aquí cuando llegas desde su detalle para una corrección administrativa.</div></div>
<div class="campo completo oculto" id="campoHorarioIntensivo"><label for="horario_intensivo_id">Horario del intensivo *</label><select id="horario_intensivo_id"><option value="">Seleccionar horario...</option><?php foreach($horariosIntensivo as $h):?><option value="<?=e($h['id'])?>" data-sede="<?=e($h['sede_clave'])?>"><?=e(substr($h['hora_inicio'],0,5).' — '.substr($h['hora_fin'],0,5))?></option><?php endforeach;?></select></div>
<div class="campo completo"><label for="nombre">Nombre completo *</label><input type="text" id="nombre" required placeholder="Nombre y apellidos"></div>
<div class="campo"><label for="fecha_nacimiento">Fecha de nacimiento</label><input type="date" id="fecha_nacimiento"><div class="ayuda">Opcional.</div></div>
<div class="campo"><label for="whatsapp">WhatsApp *</label><input type="text" id="whatsapp" required placeholder="Ej. 9981234567"></div>
<div class="campo completo"><label for="correo">Correo electrónico</label><input type="email" id="correo" placeholder="correo@ejemplo.com"></div>
<div class="campo"><label for="fecha_inicio">Fecha de inicio *</label><input type="date" id="fecha_inicio" required></div>
<div class="campo" id="campoHorario"><label for="horario_preferido_id">Horario regular *</label><select id="horario_preferido_id"><option value="">Seleccionar horario...</option><?php foreach($horarios as $h): ?><option value="<?=e($h['id'])?>" data-sede="<?=e($h['sede_clave'])?>"><?=e(substr($h['hora_inicio'],0,5).' — '.substr($h['hora_fin'],0,5))?></option><?php endforeach; ?></select></div>
<div class="campo" id="campoPlan"><label for="plan_actual_id">Plan *</label><select id="plan_actual_id"><option value="">Seleccionar plan...</option><?php foreach($planes as $p): ?><option value="<?=e($p['id'])?>" data-sede="<?=e($p['sede_clave'])?>"><?=e($p['nombre'].' — $'.number_format((float)$p['precio'],0))?></option><?php endforeach; ?></select></div>
<div class="campo completo"><label for="observaciones">Observaciones <span id="obsRequired"></span></label><textarea id="observaciones" placeholder="Notas del alumno..."></textarea><div class="ayuda" id="ayudaObs"></div></div>
</div><div class="acciones"><button type="submit" id="btnGuardar">Guardar alumno</button></div></form></div></div>
<script>
const qs=new URLSearchParams(location.search),origen=qs.get('origen'),cursoId=qs.get('curso_id'),sedeQs=(qs.get('sede')||'').toUpperCase();
const form=document.getElementById('formAlumno'),mensaje=document.getElementById('mensaje'),boton=document.getElementById('btnGuardar'),tipo=document.getElementById('tipo_ingreso'),sede=document.getElementById('sede'),campoCiclo=document.getElementById('campoCiclo'),ciclo=document.getElementById('ciclo_pago'),campoHorario=document.getElementById('campoHorario'),campoPlan=document.getElementById('campoPlan'),horario=document.getElementById('horario_preferido_id'),plan=document.getElementById('plan_actual_id'),campoCurso=document.getElementById('campoCurso'),curso=document.getElementById('curso_intensivo_id'),campoHorarioIntensivo=document.getElementById('campoHorarioIntensivo'),horarioIntensivo=document.getElementById('horario_intensivo_id'),fechaInicio=document.getElementById('fecha_inicio'),ayuda=document.getElementById('ayudaTipo'),avisoHistorico=document.getElementById('avisoHistorico'),observaciones=document.getElementById('observaciones'),obsRequired=document.getElementById('obsRequired'),ayudaObs=document.getElementById('ayudaObs'),subtitulo=document.getElementById('subtituloAlta');
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function filtrar(select){const actual=sede.value;let valida=false;[...select.options].forEach((o,i)=>{if(i===0)return;const visible=o.dataset.sede===actual;o.hidden=!visible;o.disabled=!visible;if(visible&&o.value===select.value)valida=true;});if(!valida)select.value='';}
function opcionCurso(){return curso.selectedOptions[0]||null}function esHistorico(){const o=opcionCurso();return tipo.value==='INTENSIVO'&&o&&o.dataset.historico==='1'}
function fechaCurso(){const o=opcionCurso();fechaInicio.value=o&&o.dataset.inicio?o.dataset.inicio:'';actualizarHistorico()}
function actualizarHistorico(){const hist=esHistorico();avisoHistorico.classList.toggle('oculto',!hist);obsRequired.textContent=hist?'*':'';observaciones.required=hist;ayudaObs.textContent=hist?'Obligatorio: explica por qué este alumno se está incorporando de forma retroactiva. Quedará en el historial.':'';subtitulo.textContent=hist?'Alta administrativa para completar información histórica. No reabre la inscripción del curso.':'El alumno quedará pendiente hasta registrar su primer pago válido.';if(hist)ayuda.textContent='Estás completando un curso histórico como ADMIN.'}
function actualizar(){const intensivo=tipo.value==='INTENSIVO',palapasRegular=sede.value==='PALAPAS'&&!intensivo;campoCiclo.classList.toggle('oculto',!palapasRegular);ciclo.required=palapasRegular;if(!palapasRegular)ciclo.value='';campoHorario.classList.toggle('oculto',intensivo);campoPlan.classList.toggle('oculto',intensivo);campoCurso.classList.toggle('oculto',!intensivo);campoHorarioIntensivo.classList.toggle('oculto',!intensivo);horario.required=!intensivo;plan.required=!intensivo;curso.required=intensivo;horarioIntensivo.required=intensivo;fechaInicio.readOnly=intensivo;if(intensivo){horario.value='';plan.value='';filtrar(curso);filtrar(horarioIntensivo);fechaCurso();if(!esHistorico())ayuda.textContent='El alumno se agregará al curso y horario seleccionados en el mismo paso.';}else{curso.value='';horarioIntensivo.value='';fechaInicio.readOnly=false;ayuda.textContent=sede.value==='PALAPAS'?'Planes Palapas: X3 $800 · X5 $1,000.':'El plan y el horario definen su modalidad regular; seguirá pendiente hasta su primer pago.';filtrar(horario);filtrar(plan);actualizarHistorico()}}
if(['MONTEVERDE','PALAPAS'].includes(sedeQs))sede.value=sedeQs;if(origen==='intensivo')tipo.value='INTENSIVO';if(cursoId){const preset=[...curso.options].find(o=>o.value===cursoId);if(preset){sede.value=preset.dataset.sede;curso.value=cursoId;}}
actualizar();if(cursoId&&[...curso.options].some(o=>o.value===cursoId)){curso.value=cursoId;fechaCurso();}tipo.addEventListener('change',actualizar);sede.addEventListener('change',actualizar);curso.addEventListener('change',fechaCurso);
form.addEventListener('submit',async e=>{e.preventDefault();mensaje.className='';mensaje.style.display='none';boton.disabled=true;boton.textContent='Guardando...';const intensivo=tipo.value==='INTENSIVO';const palapasRegular=sede.value==='PALAPAS'&&!intensivo;const hist=esHistorico();const obs=observaciones.value.trim();if(hist&&!obs){mensaje.className='error';mensaje.textContent='Error: escribe el motivo de la corrección histórica en Observaciones.';boton.disabled=false;boton.textContent='Guardar alumno';return}const datos={sede:sede.value,ciclo_pago:palapasRegular?ciclo.value:null,tipo_ingreso:tipo.value,nombre:document.getElementById('nombre').value.trim(),fecha_nacimiento:document.getElementById('fecha_nacimiento').value,whatsapp:document.getElementById('whatsapp').value.trim(),correo:document.getElementById('correo').value.trim(),fecha_inicio:fechaInicio.value,horario_preferido_id:intensivo?null:horario.value,plan_actual_id:intensivo?null:plan.value,curso_intensivo_id:intensivo?curso.value:null,horario_intensivo_id:intensivo?horarioIntensivo.value:null,observaciones:obs,correccion_historica:hist,motivo_correccion:hist?obs:null};try{const r=await fetch('/api/alumnos.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(datos)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'No se pudo crear el alumno');mensaje.className='exito';const cred=d.acceso_portal||{},id=d.alumno?.id||'',estado=d.alumno?.estado_administrativo||'PENDIENTE';mensaje.innerHTML=`✓ ${hist?'Alumno creado y agregado al historial del intensivo':(intensivo?'Alumno creado y agregado al intensivo':'Alumno creado')}. Estado: ${esc(estado)}.${hist?'<br>La corrección quedó auditada.':''}${cred.usuario?`<div class="cred">Portal del alumno<br>Usuario: <b>${esc(cred.usuario)}</b><br>Contraseña temporal: <b>${esc(cred.password_temporal)}</b><br>Deberá cambiarla al iniciar sesión.</div>`:''}`;if(intensivo&&d.curso_intensivo_id){setTimeout(()=>{location.href='/intensivo-detalle.php?id='+encodeURIComponent(d.curso_intensivo_id)},1200);return;}if(id){setTimeout(()=>{location.href='/ficha-alumno.php?id='+encodeURIComponent(id)},1200);return;}setTimeout(()=>{location.href='/alumnos.php?sede='+encodeURIComponent(sede.value)},1200);}catch(err){mensaje.className='error';mensaje.textContent='Error: '+err.message;}finally{boton.disabled=false;boton.textContent='Guardar alumno';}});
</script></body></html>