<?php
declare(strict_types=1);
$config = require __DIR__ . '/../config/database.php';
$pdo = new PDO("mysql:host={$config['host']};dbname={$config['dbname']};charset={$config['charset']}",$config['user'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$horarios=$pdo->query("SELECT h.id,h.hora_inicio,h.hora_fin,s.clave sede_clave FROM horarios h INNER JOIN sedes s ON s.id=h.sede_id WHERE h.activo=1 AND h.regular=1 ORDER BY s.clave,h.hora_inicio")->fetchAll();
$planes=$pdo->query("SELECT p.id,p.nombre,p.sesiones_semana,p.precio,s.clave sede_clave FROM planes p INNER JOIN sedes s ON s.id=p.sede_id WHERE p.activo=1 ORDER BY s.clave,p.sesiones_semana")->fetchAll();
?>
<!DOCTYPE html><html lang="es"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Agregar alumno — Hache Natación</title>
<style>*{box-sizing:border-box}body{margin:0;font-family:Arial,Helvetica,sans-serif;background:#f4f7fb;color:#172033}.contenedor{width:min(760px,92%);margin:40px auto}.encabezado{margin-bottom:25px}.encabezado h1{margin:0 0 8px;font-size:30px}.encabezado p{margin:0;color:#667085}.card{background:#fff;border-radius:18px;padding:30px;box-shadow:0 8px 30px rgba(0,0,0,.08)}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.campo{display:flex;flex-direction:column;gap:7px}.campo.completo{grid-column:1/-1}label{font-weight:600;font-size:14px}input,select,textarea{width:100%;padding:13px 14px;border:1px solid #d0d5dd;border-radius:10px;font-size:15px;background:#fff;outline:none}textarea{min-height:100px;resize:vertical}.ayuda{margin-top:2px;color:#667085;font-size:13px;line-height:1.4}.oculto{display:none!important}.acciones{margin-top:25px;display:flex;justify-content:flex-end}button{border:0;border-radius:10px;padding:14px 24px;background:#2563eb;color:#fff;font-size:15px;font-weight:700;cursor:pointer}button:disabled{opacity:.6;cursor:wait}#mensaje{display:none;margin-bottom:20px;padding:14px;border-radius:10px;font-weight:600;line-height:1.45}.exito{display:block!important;background:#dcfce7;color:#166534}.error{display:block!important;background:#fee2e2;color:#991b1b}.cred{margin-top:10px;padding-top:10px;border-top:1px solid #bbf7d0;font-family:monospace;font-size:14px}@media(max-width:650px){.contenedor{width:100%;margin:0;padding:72px 14px 20px}.grid{grid-template-columns:1fr}.campo.completo{grid-column:auto}.card{padding:20px}.encabezado h1{font-size:25px}}</style></head><body>
<div class="contenedor"><div class="encabezado"><h1>Agregar alumno</h1><p>El alumno quedará pendiente hasta registrar su primer pago válido.</p></div><div id="mensaje"></div><div class="card"><form id="formAlumno"><div class="grid">
<div class="campo completo"><label for="sede">Sede *</label><select id="sede" required><option value="MONTEVERDE">Monteverde</option><option value="PALAPAS">Palapas</option></select></div>
<div class="campo completo"><label for="tipo_ingreso">Tipo de ingreso *</label><select id="tipo_ingreso" required><option value="REGULAR">Alumno regular</option><option value="INTENSIVO">Curso intensivo</option></select><div class="ayuda" id="ayudaTipo"></div></div>
<div class="campo completo oculto" id="campoCiclo"><label for="ciclo_pago">Ciclo de pago Palapas *</label><select id="ciclo_pago"><option value="">Seleccionar...</option><option value="P1">P1 — renovación día 1</option><option value="P15">P15 — renovación día 15</option></select><div class="ayuda">La mensualidad sigue siendo mensual; solo cambia el día de renovación.</div></div>
<div class="campo completo"><label for="nombre">Nombre completo *</label><input type="text" id="nombre" required placeholder="Nombre y apellidos"></div>
<div class="campo"><label for="fecha_nacimiento">Fecha de nacimiento</label><input type="date" id="fecha_nacimiento"><div class="ayuda">Opcional.</div></div>
<div class="campo"><label for="whatsapp">WhatsApp *</label><input type="text" id="whatsapp" required placeholder="Ej. 9981234567"></div>
<div class="campo completo"><label for="correo">Correo electrónico</label><input type="email" id="correo" placeholder="correo@ejemplo.com"></div>
<div class="campo"><label for="fecha_inicio">Fecha de inicio *</label><input type="date" id="fecha_inicio" required></div>
<div class="campo" id="campoHorario"><label for="horario_preferido_id">Horario regular *</label><select id="horario_preferido_id"><option value="">Seleccionar horario...</option><?php foreach($horarios as $h): ?><option value="<?= htmlspecialchars($h['id']) ?>" data-sede="<?= htmlspecialchars($h['sede_clave']) ?>"><?= htmlspecialchars(substr($h['hora_inicio'],0,5)) ?> — <?= htmlspecialchars(substr($h['hora_fin'],0,5)) ?></option><?php endforeach; ?></select></div>
<div class="campo" id="campoPlan"><label for="plan_actual_id">Plan *</label><select id="plan_actual_id"><option value="">Seleccionar plan...</option><?php foreach($planes as $p): ?><option value="<?= htmlspecialchars($p['id']) ?>" data-sede="<?= htmlspecialchars($p['sede_clave']) ?>"><?= htmlspecialchars($p['nombre']) ?> — $<?= number_format((float)$p['precio'],0) ?></option><?php endforeach; ?></select></div>
<div class="campo completo"><label for="observaciones">Observaciones</label><textarea id="observaciones" placeholder="Notas del alumno..."></textarea></div>
</div><div class="acciones"><button type="submit" id="btnGuardar">Guardar alumno</button></div></form></div></div>
<script>
const qs=new URLSearchParams(location.search),origen=qs.get('origen'),cursoId=qs.get('curso_id'),sedeQs=(qs.get('sede')||'').toUpperCase();
const form=document.getElementById('formAlumno'),mensaje=document.getElementById('mensaje'),boton=document.getElementById('btnGuardar'),tipo=document.getElementById('tipo_ingreso'),sede=document.getElementById('sede'),campoCiclo=document.getElementById('campoCiclo'),ciclo=document.getElementById('ciclo_pago'),campoHorario=document.getElementById('campoHorario'),campoPlan=document.getElementById('campoPlan'),horario=document.getElementById('horario_preferido_id'),plan=document.getElementById('plan_actual_id'),ayuda=document.getElementById('ayudaTipo');
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function filtrar(select){const actual=sede.value;let valida=false;[...select.options].forEach((o,i)=>{if(i===0)return;const visible=o.dataset.sede===actual;o.hidden=!visible;o.disabled=!visible;if(visible&&o.value===select.value)valida=true;});if(!valida)select.value='';}
function actualizar(){const intensivo=tipo.value==='INTENSIVO',palapasRegular=sede.value==='PALAPAS'&&!intensivo;campoCiclo.classList.toggle('oculto',!palapasRegular);ciclo.required=palapasRegular;if(!palapasRegular)ciclo.value='';campoHorario.classList.toggle('oculto',intensivo);campoPlan.classList.toggle('oculto',intensivo);horario.required=!intensivo;plan.required=!intensivo;if(intensivo){horario.value='';plan.value='';ayuda.textContent='El horario se asigna dentro del curso intensivo.';}else ayuda.textContent=sede.value==='PALAPAS'?'Planes Palapas: X3 $800 · X5 $1,000.':'El plan y el horario definen su modalidad regular; seguirá pendiente hasta su primer pago.';filtrar(horario);filtrar(plan);}
if(['MONTEVERDE','PALAPAS'].includes(sedeQs))sede.value=sedeQs;if(origen==='intensivo')tipo.value='INTENSIVO';actualizar();tipo.addEventListener('change',actualizar);sede.addEventListener('change',actualizar);
form.addEventListener('submit',async e=>{e.preventDefault();mensaje.className='';mensaje.style.display='none';boton.disabled=true;boton.textContent='Guardando...';const intensivo=tipo.value==='INTENSIVO';const palapasRegular=sede.value==='PALAPAS'&&!intensivo;const datos={sede:sede.value,ciclo_pago:palapasRegular?ciclo.value:null,tipo_ingreso:tipo.value,nombre:document.getElementById('nombre').value.trim(),fecha_nacimiento:document.getElementById('fecha_nacimiento').value,whatsapp:document.getElementById('whatsapp').value.trim(),correo:document.getElementById('correo').value.trim(),fecha_inicio:document.getElementById('fecha_inicio').value,horario_preferido_id:intensivo?null:horario.value,plan_actual_id:intensivo?null:plan.value,observaciones:document.getElementById('observaciones').value.trim()};try{const r=await fetch('/api/alumnos.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(datos)}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'No se pudo crear el alumno');mensaje.className='exito';const cred=d.acceso_portal||{},id=d.alumno?.id||'';mensaje.innerHTML=`✓ Alumno creado${d.alumno?.ciclo_pago?` · ${esc(d.alumno.ciclo_pago)}`:''}. Estado: PENDIENTE hasta su primer pago válido.${cred.usuario?`<div class="cred">Portal del alumno<br>Usuario: <b>${esc(cred.usuario)}</b><br>Contraseña temporal: <b>${esc(cred.password_temporal)}</b><br>Deberá cambiarla al iniciar sesión.</div>`:''}`;if(origen==='intensivo'&&cursoId){setTimeout(()=>{location.href='/intensivo-detalle.php?id='+encodeURIComponent(cursoId)+(id?'&alumno_nuevo='+encodeURIComponent(id):'')},1200);return;}if(id){setTimeout(()=>{location.href='/ficha-alumno.php?id='+encodeURIComponent(id)},1200);return;}setTimeout(()=>{location.href='/alumnos.php?sede='+encodeURIComponent(sede.value)},1200);}catch(err){mensaje.className='error';mensaje.textContent='Error: '+err.message;}finally{boton.disabled=false;boton.textContent='Guardar alumno';}});
</script></body></html>