<?php
declare(strict_types=1);
require_once __DIR__.'/../config/auth.php';
page_require(['ADMIN','VERIFICADOR']);
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Obligaciones y saldos — Hache Natación</title><style>
*{box-sizing:border-box}body{margin:0;background:#f3f6fa;color:#172033;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif}.wrap{max-width:1080px;margin:auto;padding:32px 14px 44px}.head{display:flex;justify-content:space-between;gap:14px;align-items:end;margin-bottom:16px}.ey{font-size:11px;text-transform:uppercase;font-weight:900;letter-spacing:.1em;color:#64748b}h1{font-size:27px;margin:4px 0 4px}.sub{font-size:13px;color:#64748b}.control{display:grid;gap:5px;min-width:180px}.control label{font-size:10px;text-transform:uppercase;font-weight:900;color:#64748b}.control input{border:1px solid #cbd5e1;border-radius:10px;background:#fff;min-height:42px;padding:8px 10px;font:inherit}.grid{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.card{background:#fff;border:1px solid #e6ebf1;border-radius:15px;padding:14px;box-shadow:0 5px 18px rgba(15,23,42,.035)}.card.wide{grid-column:span 2}.k{font-size:10px;text-transform:uppercase;letter-spacing:.06em;font-weight:900;color:#64748b}.v{font-size:24px;font-weight:900;margin-top:5px}.s{font-size:12px;color:#64748b;margin-top:5px;line-height:1.4}.section{margin-top:18px}.section h2{font-size:18px;margin:0 0 10px}.closebox{display:grid;grid-template-columns:repeat(3,1fr);gap:9px}.note{background:#eef4f8;border-radius:12px;padding:12px;font-size:12px;color:#475569;line-height:1.5}.delta.pos{color:#166534}.delta.neg{color:#991b1b}.toolbar{display:flex;gap:8px;align-items:center;justify-content:space-between;margin-bottom:9px}.filters{display:flex;gap:7px;flex-wrap:wrap}.chip{border:1px solid #cbd5e1;background:#fff;border-radius:999px;padding:8px 11px;font-weight:850;font-size:12px;cursor:pointer}.chip.active{background:#172033;color:#fff;border-color:#172033}.count{font-size:12px;color:#64748b}.tablewrap{overflow:auto;background:#fff;border:1px solid #e6ebf1;border-radius:15px}table{width:100%;border-collapse:collapse;min-width:840px}th,td{text-align:left;padding:11px 12px;border-bottom:1px solid #edf2f7;font-size:12px}th{font-size:10px;text-transform:uppercase;letter-spacing:.05em;color:#64748b;background:#f8fafc;position:sticky;top:0}tr:last-child td{border-bottom:0}.name{font-weight:850}.muted{color:#64748b}.money{font-variant-numeric:tabular-nums;font-weight:800}.status{display:inline-block;padding:5px 8px;border-radius:999px;font-size:10px;font-weight:900}.status.PAGADO{background:#dcfce7;color:#166534}.status.ANTICIPO{background:#fef3c7;color:#92400e}.status.PENDIENTE{background:#fee2e2;color:#991b1b}.empty{padding:24px;text-align:center;color:#64748b}.error{color:#991b1b;font-weight:800}@media(max-width:760px){.head{align-items:stretch;flex-direction:column}.control{min-width:0}.grid,.closebox{grid-template-columns:1fr 1fr}.card.wide{grid-column:span 2}}@media(max-width:480px){.grid,.closebox{grid-template-columns:1fr}.card.wide{grid-column:auto}.toolbar{align-items:flex-start;flex-direction:column}}
</style></head><body><main class="wrap"><div class="head"><div><div class="ey">Fase 2 · lectura financiera</div><h1>Obligaciones y saldos</h1><div class="sub">Obligación registrada, pagos válidos, saldo y comparación con cierre histórico.</div></div><div class="control"><label>Periodo financiero</label><input id="periodo" type="month"></div></div><div id="contenido"><div class="empty">Cargando…</div></div></main><script>
const qs=new URLSearchParams(location.search),SEDE=(qs.get('sede')||localStorage.getItem('hache_sede')||'MONTEVERDE').toUpperCase();
const $=id=>document.getElementById(id),money=n=>Number(n||0).toLocaleString('es-MX',{style:'currency',currency:'MXN',minimumFractionDigits:0,maximumFractionDigits:2});
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const fmtDate=v=>{if(!v)return'—';const d=String(v).slice(0,10).split('-');return d.length===3?`${d[2]}/${d[1]}/${d[0]}`:v};
const now=new Date();$('periodo').value=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}`;
let DATA=null,FILTER='SALDO';
function card(k,v,s='',wide=false){return `<div class="card ${wide?'wide':''}"><div class="k">${esc(k)}</div><div class="v">${esc(v)}</div>${s?`<div class="s">${esc(s)}</div>`:''}</div>`}
function delta(n){const x=Number(n||0),cls=x>0?'pos':x<0?'neg':'';return `<span class="delta ${cls}">${x>0?'+':''}${money(x)}</span>`}
function renderClose(x){if(!x.cierre)return `<section class="section"><h2>Cierre histórico</h2><div class="note">Este periodo no tiene cierre guardado. La lectura actual usa el rango financiero mostrado y no crea ni modifica cierres.</div></section>`;const c=x.comparacion_cierre;return `<section class="section"><h2>Cierre histórico vs cálculo actual</h2><div class="closebox"><div class="card"><div class="k">Cierre guardado</div><div class="v">${money(c.total_cierre)}</div><div class="s">${fmtDate(x.cierre.cerrado_at)} · ${esc(x.cierre.cerrado_por_usuario||'')}</div></div><div class="card"><div class="k">Cálculo actual</div><div class="v">${money(c.total_actual)}</div><div class="s">Mismas reglas del periodo financiero.</div></div><div class="card"><div class="k">Diferencia posterior</div><div class="v">${delta(c.diferencia_total)}</div><div class="s">No sobrescribe el cierre guardado.</div></div></div></section>`}
function renderRows(){if(!DATA)return;const rows=DATA.obligaciones.filter(o=>FILTER==='TODAS'||(FILTER==='SALDO'&&Number(o.saldo)>0.009)||o.tipo===FILTER);$('tbody').innerHTML=rows.length?rows.map(o=>`<tr><td><div class="name">${esc(o.alumno)}</div><div class="muted">${esc(o.tipo)}</div></td><td>${esc(o.referencia)}</td><td><div>${esc(o.periodo_obligacion)}</div><div class="muted">Ref. ${fmtDate(o.fecha_referencia)}</div></td><td class="money">${money(o.total)}</td><td class="money">${money(o.pagado)}<div class="muted">${o.pagos_validos} válido(s)${o.pagos_invalidados?` · ${o.pagos_invalidados} invalidado(s)`:''}</div></td><td class="money">${money(o.saldo)}</td><td><span class="status ${o.estado_pago}">${esc(o.estado_pago)}</span></td></tr>`).join(''):'<tr><td colspan="7" class="empty">No hay obligaciones para este filtro.</td></tr>';$('count').textContent=`${rows.length} de ${DATA.obligaciones.length}`;document.querySelectorAll('.chip').forEach(b=>b.classList.toggle('active',b.dataset.f===FILTER));}
function render(x){DATA=x;const r=x.obligaciones_resumen,rg=x.periodo.rango,partner=x.reparto.socio_nombre||'Socio';$('contenido').innerHTML=`<div class="grid">${card('Ingresos del periodo',money(x.ingresos.total),`${x.ingresos.pagos} pagos válidos`,true)}${card('Obligaciones registradas',money(r.total),`${r.obligaciones} obligaciones`)}${card('Saldo cuantificado',money(r.saldo),`${r.con_saldo} con saldo`)}${card('Para Hache',money(x.reparto.hache))}${card('Para '+partner,money(x.reparto.socio))}</div><section class="section"><div class="note"><strong>Periodo financiero ${esc(x.periodo.clave)}:</strong> ${fmtDate(rg.inicio)} → ${fmtDate(rg.cierre)}${rg.personalizado?' · rango personalizado':''}. El periodo de obligación y la fecha de cobro se conservan por separado.</div></section>${renderClose(x)}<section class="section"><div class="toolbar"><div class="filters"><button class="chip active" data-f="SALDO">Con saldo</button><button class="chip" data-f="TODAS">Todas</button><button class="chip" data-f="MENSUALIDAD">Mensualidades</button><button class="chip" data-f="INTENSIVO">Intensivos</button><button class="chip" data-f="INSCRIPCION">Inscripciones</button></div><div id="count" class="count"></div></div><div class="tablewrap"><table><thead><tr><th>Alumno / concepto</th><th>Referencia</th><th>Periodo obligación</th><th>Total</th><th>Pagado</th><th>Saldo</th><th>Estado</th></tr></thead><tbody id="tbody"></tbody></table></div></section><section class="section"><div class="note">Saldo = obligación registrada − pagos <strong>VALIDO</strong>. Los pagos invalidados no reducen el saldo. Un cierre guardado es histórico y nunca se recalcula desde esta vista.</div></section>`;document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{FILTER=b.dataset.f;renderRows()});renderRows();}
async function load(){const p=$('periodo').value,c=$('contenido');if(!p)return;c.innerHTML='<div class="empty">Cargando…</div>';try{const r=await fetch(`/api/finanzas-internas.php?periodo=${encodeURIComponent(p)}&sede=${encodeURIComponent(SEDE)}`),x=await r.json();if(!r.ok||!x.ok)throw new Error(x.error||'No se pudo cargar');render(x)}catch(e){c.innerHTML='<div class="empty error">'+esc(e.message)+'</div>'}}
$('periodo').addEventListener('change',load);load();
</script></body></html>