<!DOCTYPE html>
<html lang="es">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta name="theme-color" content="#123b5d">
<link rel="manifest" href="/manifest.webmanifest">
<link rel="icon" href="/assets/icons/hache-icon.svg" type="image/svg+xml">
<title>Hache Natación</title>
<style>*{box-sizing:border-box}body{margin:0;min-height:100vh;font-family:Arial,sans-serif;background:#f4f7f9;display:flex;align-items:center;justify-content:center}.login-container{width:100%;max-width:380px;padding:20px}.login-box{background:#fff;padding:35px 30px;border-radius:16px;box-shadow:0 10px 35px rgba(0,0,0,.10)}.logo{text-align:center;margin-bottom:30px}.logo h1{margin:0;font-size:30px;color:#123b5d}.logo p{margin:6px 0 0;color:#777;font-size:14px}.form-group{margin-bottom:18px}.form-group label{display:block;margin-bottom:7px;font-size:14px;color:#333}.form-group input{width:100%;padding:13px 14px;border:1px solid #d5dce1;border-radius:9px;font-size:16px;outline:none}.form-group input:focus{border-color:#1976a8}button{width:100%;padding:14px;border:0;border-radius:9px;background:#1976a8;color:#fff;font-size:16px;font-weight:bold;cursor:pointer}button:disabled{opacity:.6;cursor:wait}#error{display:none;margin-bottom:15px;padding:11px;border-radius:8px;background:#ffe8e8;color:#b00020;font-size:14px;text-align:center}</style>
</head><body><div class="login-container"><div class="login-box"><div class="logo"><h1>Hache Natación</h1><p>Acceso al sistema</p></div><div id="error"></div><form id="loginForm"><div class="form-group"><label for="usuario">Usuario</label><input type="text" id="usuario" autocomplete="username" required></div><div class="form-group"><label for="password">Contraseña</label><input type="password" id="password" autocomplete="current-password" required></div><button type="submit" id="btnLogin">Iniciar sesión</button></form></div></div><script>const form=document.getElementById('loginForm'),errorBox=document.getElementById('error'),button=document.getElementById('btnLogin');form.addEventListener('submit',async e=>{e.preventDefault();errorBox.style.display='none';button.disabled=true;button.textContent='Iniciando sesión...';try{const response=await fetch('/api/login.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({usuario:document.getElementById('usuario').value.trim(),password:document.getElementById('password').value})});const data=await response.json();if(data.ok){sessionStorage.setItem('hache_usuario',JSON.stringify(data.usuario));window.location.href=data.redirect||'/dashboard.php';}else{errorBox.textContent=data.error||'Usuario o contraseña incorrectos';errorBox.style.display='block';}}catch(error){errorBox.textContent='No se pudo conectar con el servidor.';errorBox.style.display='block';}button.disabled=false;button.textContent='Iniciar sesión';});</script><script src="/assets/pwa.js" defer></script></body></html>