<?php
declare(strict_types=1);
require_once __DIR__.'/../config/auth.php';
page_require(['ADMIN']);
?>
<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Aprendizaje Sharky</title>
<style>*{box-sizing:border-box}body{margin:0;background:#f3f6fa;font-family:Arial,sans-serif;color:#172033}.wrap{max-width:1180px;margin:auto;padding:72px 14px 40px}.top{display:flex;justify-content:space-between;gap:12px;align-items:center;flex-wrap:wrap}.top a{color:#123b5d;font-weight:800;text-decoration:none}.grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin:14px 0}.card,.case{background:#fff;border-radius:14px;padding:14px;box-shadow:0 2px 10px rgba(15,23,42,.05)}.card strong{display:block;font-size:24px}.card span,.meta{color:#64748b;font-size:12px}.case{margin:10px 0}.head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;flex-wrap:wrap}.pill{display:inline-block;padding:5px 8px;border-radius:999px;background:#eef2f7;font-size:12px;font-weight:800}.high{background:#fff0ef;color:#a1261c}.good{background:#e8f7ee;color:#176b3a}.body{margin-top:10px;line-height:1.45}.body p{margin:6px 0}.filters button,.btn{border:0;border-radius:8px;padding:8px 10px;font-weight:800;cursor:pointer}.filters button{background:#e7edf4;color:#123b5d}.btn{background:#123b5d;color:#fff;margin-right:6px}.empty{color:#64748b;padding:20px 0}@media(max-width:700px){.grid{grid-template-columns:repeat(2,1fr)}}</style></head><body><main class="wrap">
<div class="top"><div><h1 style="margin:0">Bandeja de aprendizaje de Sharky</h1><p class="meta">Hallazgos automáticos + veredictos de revisión. El texto de WhatsApp no se guarda aquí.</p></div><a href="/sharky-admin.php">← Sharky</a></div>
<div class="grid" id="cards"></div><div class="filters"><button data-status="">Todos</button> <button data-status="PENDING">Pendientes</button> <button data-status="APPROVED">Aprobados</button> <button data-status="DISMISSED">Descartados</button></div><section id="cases"></section>
</main><script>
const C=document.getElementById('cards'),L=document.getElementById('cases');const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function load(status=''){const r=await fetch('/api/sharky-learning.php'+(status?'?status='+encodeURIComponent(status):'')),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Error');const s=d.summary||{};C.innerHTML=`<div class="card"><strong>${s.pending||0}</strong><span>Pendientes</span></div><div class="card"><strong>${s.approved||0}</strong><span>Aprobados</span></div><div class="card"><strong>${s.errors||0}</strong><span>Errores reales</span></div><div class="card"><strong>${s.good_patterns||0}</strong><span>Patrones positivos</span></div>`;L.innerHTML=(d.cases||[]).length?(d.cases||[]).map(x=>`<article class="case"><div class="head"><div><strong>${esc(x.verdict||'Pendiente de revisión')}</strong><div class="meta">${esc(x.case_kind)} · ${esc(x.finding_type||x.classification||'')} · ${esc(x.created_at)}</div></div><span class="pill ${x.priority==='HIGH'||x.priority==='CRITICAL'?'high':x.verdict==='GOOD_PATTERN'?'good':''}">${esc(x.priority)} · ${esc(x.status)}</span></div><div class="body"><p><b>Área:</b> ${esc(x.rule_area||'—')}</p><p><b>Veredicto:</b> ${esc(x.rationale||'Aún sin revisión.')}</p><p><b>Debió ocurrir:</b> ${esc(x.expected_behavior||'—')}</p><p><b>Recomendación:</b> ${esc(x.recommendation||'—')}</p><p><b>Regresión:</b> ${Number(x.regression_required)?'Sí':'No'} ${x.reviewer?'· '+esc(x.reviewer):''}</p></div>${x.status==='PENDING'?'':`<div class="meta">Revisado: ${esc(x.reviewed_at||'—')}</div>`}</article>`).join(''):'<div class="empty">No hay casos en esta vista.</div>'}
document.querySelectorAll('[data-status]').forEach(b=>b.onclick=()=>load(b.dataset.status));load().catch(e=>L.textContent=e.message);
</script></body></html>
