<?php
declare(strict_types=1);
require_once __DIR__.'/../config/auth.php';
page_require(['ADMIN']);
?><!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Usuarios — Hache Natación</title><style>*{box-sizing:border-box}body{margin:0;background:#f3f6fa;color:#172033;font-family:Arial,sans-serif}.wrap{max-width:980px;margin:auto;padding:84px 14px 30px}h1{margin:0 0 5px}.sub{color:#64748b;margin-bottom:18px}.grid{display:grid;grid-template-columns:1fr;gap:14px}.card{background:#fff;border-radius:16px;padding:16px;box-shadow:0 4px 16px #0000000d}.form{display:grid;grid-template-columns:1fr 1fr;gap:10px}.form .wide{grid-column:1/-1}label{display:block;font-size:11px;font-weight:800;color:#64748b;margin-bottom:5px;text-transform:uppercase}input,select{width:100%;padding:11px;border:1px solid #cbd5e1;border-radius:9px;font-size:15px}button{border:0;border-radius:9px;padding:10px 12px;font-weight:800;cursor:pointer}.primary{background:#1976a8;color:#fff}.ghost{background:#e8eef2;color:#334155}.danger{background:#fee2e2;color:#991b1b}.usuario{display:grid;grid-template-columns:1fr auto;gap:10px;padding:12px 0;border-top:1px solid #eef2f7}.usuario:first-child{border-top:0}.name{font-weight:800}.meta{font-size:12px;color:#64748b;margin-top:3px}.actions{display:flex;gap:6px;align-items:center;flex-wrap:wrap}.badge{display:inline-block;padding:4px 7px;border-radius:999px;font-size:10px;font-weight:900;background:#e2e8f0}.msg{margin:10px 0;font-size:13px;font-weight:700;color:#166534}.err{color:#991b1b}@media(max-width:620px){.form{grid-template-columns:1fr}.form .wide{grid-column:auto}.usuario{grid-template-columns:1fr}.actions button{flex:1}}</style></head><body><main class="wrap"><h1>Usuarios</h1><div class="sub">Accesos y roles del sistema</div><div class="grid"><section class="card"><h2>Crear usuario</h2><div id="msg" class="msg"></div><div class="form"><div><label>Usuario</label><input id="usuario"></div><div><label>Contraseña</label><input id="password" type="password" minlength="6"></div><div><label>Rol</label><select id="rol"><option>ADMIN</option><option>VERIFICADOR</option><option>ALUMNO</option></select></div><div id="alumnoWrap" style="display:none"><label>Alumno vinculado</label><select id="alumno"><option value="">Seleccionar…</option></select></div><div class="wide"><button id="crear" class="primary">Crear usuario</button></div></div></section><section class="card"><h2>Usuarios existentes</h2><div id="lista">Cargando…</div></section></div></main><script>
const lista=document.getElementById('lista'),rol=document.getElementById('rol'),alumno=document.getElementById('alumno'),alumnoWrap=document.getElementById('alumnoWrap'),msg=document.getElementById('msg');
rol.onchange=()=>alumnoWrap.style.display=rol.value==='ALUMNO'?'block':'none';
async function api(body){const r=await fetch('/api/usuarios.php',body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{}),d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Error');return d}
async function cargar(){try{const d=await api();alumno.innerHTML='<option value="">Seleccionar…</option>'+d.alumnos_disponibles.map(a=>`<option value="${a.id}">${a.nombre}</option>`).join('');lista.innerHTML=d.usuarios.map(u=>`<div class="usuario"><div><div class="name">${u.usuario} <span class="badge">${u.rol}</span></div><div class="meta">${u.alumno_nombre?u.alumno_nombre+' · ':''}${u.activo==1?'Activo':'Inactivo'}${u.last_login?' · Último acceso '+u.last_login:''}</div></div><div class="actions"><button class="ghost" data-pass="${u.id}">Contraseña</button><button class="${u.activo==1?'danger':'primary'}" data-state="${u.id}" data-active="${u.activo==1?0:1}">${u.activo==1?'Desactivar':'Activar'}</button></div></div>`).join('')||'No hay usuarios.'}catch(e){lista.textContent=e.message}}
document.getElementById('crear').onclick=async()=>{msg.textContent='';try{await api({accion:'CREAR',usuario:document.getElementById('usuario').value.trim(),password:document.getElementById('password').value,rol:rol.value,alumno_id:alumno.value||null});msg.textContent='Usuario creado.';document.getElementById('usuario').value='';document.getElementById('password').value='';await cargar()}catch(e){msg.textContent=e.message;msg.classList.add('err')}};
lista.onclick=async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.dataset.state){await api({accion:'ESTADO',id:b.dataset.state,activo:Number(b.dataset.active)});await cargar()}if(b.dataset.pass){const p=prompt('Nueva contraseña (mínimo 6 caracteres):');if(p){await api({accion:'PASSWORD',id:b.dataset.pass,password:p});alert('Contraseña actualizada.')}}}catch(err){alert(err.message)}};cargar();
</script></body></html>