<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');require_once __DIR__.'/../config/auth.php';require_once __DIR__.'/../config/dashboard-tiempo.php';require_once __DIR__.'/../config/prospect-followup-alert.php';require_once __DIR__.'/../config/consecutive-absence-alert.php';require_once __DIR__.'/../config/intensive-no-continuity-alert.php';require_once __DIR__.'/../config/intensive-balance-source.php';auth_require(['ADMIN','VERIFICADOR']);$c=require __DIR__.'/../config/database.php';$pdo=new PDO("mysql:host={$c['host']};dbname={$c['dbname']};charset={$c['charset']}",$c['user'],$c['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);function out(array$d,int$c=200):never{http_response_code($c);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
try{$clave=auth_resolve_sede_clave((string)($_GET['sede']??'MONTEVERDE'));$st=$pdo->prepare('SELECT * FROM sedes WHERE clave=:c AND activo=1');$st->execute([':c'=>$clave]);$s=$st->fetch();if(!$s)out(['ok'=>false,'error'=>'Sede inválida'],422);$sid=$s['id'];$hoy=hache_instante_operativo();$hoyFecha=$hoy->format('Y-m-d');$mes=(int)$hoy->format('n');$anio=(int)$hoy->format('Y');$alertas=[];$f5Settings=hache_internal_alert_settings($pdo);
// Los registros públicos son alerta administrativa prioritaria durante 7 días.
if(auth_user()['rol']==='ADMIN'){try{$st=$pdo->prepare("SELECT rp.alumno_id,rp.tipo,rp.created_at,a.nombre FROM registros_publicos rp JOIN alumnos a ON a.id=rp.alumno_id WHERE rp.sede_id=:s AND rp.created_at>=DATE_SUB(NOW(),INTERVAL 7 DAY) AND a.estado_administrativo='PENDIENTE' ORDER BY rp.created_at DESC");$st->execute([':s'=>$sid]);foreach($st as$r)$alertas[]=['tipo'=>'NUEVO_USUARIO','nivel'=>'ALTA','titulo'=>'🚨 Nuevo usuario registrado','detalle'=>$r['nombre'].' · '.($r['tipo']==='INTENSIVO'?'Intensivo':'Regular').' · '.$s['nombre'],'href'=>'/ficha-alumno.php?id='.rawurlencode((string)$r['alumno_id'])];}catch(Throwable$e){error_log('[alertas] No se pudieron cargar registros públicos: '.$e->getMessage());}}
// F5: alerta global ADMIN de gestión interna pendiente. No envía mensajes ni altera Sharky.
if(auth_user()['rol']==='ADMIN'){try{$seguimiento=hache_internal_prospect_followup_summary(hache_internal_prospect_followup_candidates($pdo,$hoy,$f5Settings));$n=(int)$seguimiento['total'];if($n>0){$p=[];$ps=$seguimiento['por_sede'];if(($ps['MONTEVERDE']??0)>0)$p[]='Monteverde '.(int)$ps['MONTEVERDE'];if(($ps['PALAPAS']??0)>0)$p[]='Palapas '.(int)$ps['PALAPAS'];if(($ps['SIN_SEDE']??0)>0)$p[]='sin sede '.(int)$ps['SIN_SEDE'];$hours=(int)$f5Settings['prospect_followup_hours'];$alertas[]=['tipo'=>'PROSPECTO','nivel'=>'NEUTRA','titulo'=>"$n prospecto".($n===1?'':'s')." sin seguimiento interno por {$hours} h",'detalle'=>'Regla interna desde el último contacto verificable. '.implode(' · ',$p).'. No envía mensajes al prospecto.','href'=>'/prospectos.php'];}}catch(Throwable$e){error_log('[alertas] No se pudo evaluar seguimiento interno de prospectos: '.$e->getMessage());}}
// F5: rachas de asistencia registradas. Solo lectura; sin inferir ausencias por huecos.
try{foreach(hache_internal_consecutive_absence_candidates($pdo,(string)$sid,null,$f5Settings) as$r){$partes=[];$ua=(int)$r['umbral_ausencias'];$ui=(int)$r['umbral_no_justificadas'];if((int)$r['ausencias_consecutivas']>=$ua)$partes[]='Al menos '.$ua.' ausencias consecutivas registradas';if((int)$r['no_justificadas_consecutivas']>=$ui)$partes[]='al menos '.$ui.' no justificadas consecutivas';$alertas[]=['tipo'=>'ASISTENCIA','nivel'=>'NEUTRA','titulo'=>(string)$r['alumno_nombre'].' · revisar ausencias consecutivas','detalle'=>implode(' · ',$partes).'. Solo se usan marcas de sesiones realizadas y cerradas.','href'=>'/ficha-alumno.php?id='.rawurlencode((string)$r['alumno_id'])];}}catch(Throwable$e){error_log('[alertas] No se pudieron evaluar ausencias consecutivas: '.$e->getMessage());}
// F5: intensivo terminado sin continuidad. Inactivo mientras días/alcance sigan vacíos en Configuración.
try{foreach(hache_internal_intensive_no_continuity_candidates($pdo,(string)$sid,$hoy,$f5Settings) as$r){$estado=$r['continua_regular']===null?'continuidad sin evaluar':'marcado que no continúa';$dias=(int)$r['dias_configurados'];$alertas[]=['tipo'=>'CONTINUIDAD','nivel'=>'NEUTRA','titulo'=>(string)$r['alumno_nombre'].' · intensivo sin continuidad','detalle'=>'Finalizó el '.date('d/m/Y',strtotime((string)$r['fecha_fin'])).' · '.$estado.' · umbral configurado: '.$dias.' día'.($dias===1?'':'s').' después.','href'=>'/intensivo-detalle.php?id='.rawurlencode((string)$r['curso_id']).'&sede='.rawurlencode($clave)];}}catch(Throwable$e){error_log('[alertas] No se pudo evaluar continuidad de intensivos terminados: '.$e->getMessage());}
// F5/F2: saldos de intensivo pendientes. Misma fuente financiera que usa el Centro de pendientes.
try{$saldoResumen=hache_intensive_pending_balance_summary(hache_intensive_pending_balance_candidates($pdo,(string)$sid));$n=(int)$saldoResumen['total'];if($n>0){$saldo=(float)$saldoResumen['saldo'];$alertas[]=['tipo'=>'SALDO','nivel'=>'NEUTRA','titulo'=>"$n alumno".($n===1?'':'s').' con saldo de intensivo pendiente','detalle'=>'Saldo total verificable: $'.number_format($saldo,2,'.',',').' MXN. Solo suma pagos VALIDOS del mismo alumno y curso.','href'=>'/pendientes.php'];}}catch(Throwable$e){error_log('[alertas] No se pudieron evaluar saldos pendientes de intensivo: '.$e->getMessage());}
$st=$pdo->prepare("SELECT COUNT(*) FROM alumnos a WHERE a.sede_id=:s AND a.estado_administrativo='ACTIVO' AND a.plan_actual_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM mensualidades m WHERE m.alumno_id=a.id AND m.sede_id=a.sede_id AND m.estado='PAGADA' AND :hoy BETWEEN m.periodo_inicio AND m.periodo_fin) AND NOT EXISTS(SELECT 1 FROM curso_intensivo_alumnos cia JOIN cursos_intensivos ci ON ci.id=cia.curso_intensivo_id WHERE cia.alumno_id=a.id AND ci.sede_id=:sc AND ci.estado IN ('PROGRAMADO','EN_CURSO'))");$st->execute([':s'=>$sid,':hoy'=>$hoyFecha,':sc'=>$sid]);$n=(int)$st->fetchColumn();if($n)$alertas[]=['tipo'=>'PAGO','nivel'=>'ALTA','titulo'=>"$n alumno".($n===1?'':'s').' sin mensualidad vigente','detalle'=>'Revisar pagos pendientes antes de permitir acceso a clase.','href'=>'/alumnos.php?alerta=sin_pago&sede='.rawurlencode($clave)];
$man=$hoy->modify('+1 day')->format('Y-m-d');$st=$pdo->prepare("SELECT COUNT(*) FROM avisos_ausencia aa JOIN alumnos a ON a.id=aa.alumno_id WHERE a.sede_id=:s AND aa.estado='ACTIVO' AND :f BETWEEN aa.fecha_desde AND aa.fecha_hasta");$st->execute([':s'=>$sid,':f'=>$man]);$n=(int)$st->fetchColumn();if($n)$alertas[]=['tipo'=>'AUSENCIA','nivel'=>'MEDIA','titulo'=>"$n aviso".($n===1?'':'s').' de ausencia para mañana','detalle'=>'La asistencia los marcará como justificadas si no se presentan.','href'=>'/ausencias.php?alerta=manana&sede='.rawurlencode($clave)];
$st=$pdo->prepare("SELECT COUNT(*) FROM reposiciones_regulares rr JOIN alumnos a ON a.id=rr.alumno_id WHERE rr.estado='DISPONIBLE' AND a.sede_id=:s");$st->execute([':s'=>$sid]);$n=(int)$st->fetchColumn();if($n)$alertas[]=['tipo'=>'REPOSICION','nivel'=>'BAJA','titulo'=>"$n reposición".($n===1?'':'es').' disponible'.($n===1?'':'s'),'detalle'=>'Hay reposiciones pendientes de asignar o utilizar.','href'=>'/ausencias.php?alerta=reposiciones&sede='.rawurlencode($clave)];
$dias=(int)($pdo->query("SELECT valor FROM configuracion WHERE clave='alerta_dias_fin_intensivo' LIMIT 1")->fetchColumn()?:7);$lim=$hoy->modify("+$dias days")->format('Y-m-d');$st=$pdo->prepare("SELECT id,fecha_fin FROM cursos_intensivos WHERE sede_id=:s AND estado='EN_CURSO' AND fecha_fin BETWEEN :h AND :l ORDER BY fecha_fin");$st->execute([':s'=>$sid,':h'=>$hoyFecha,':l'=>$lim]);foreach($st as$r)$alertas[]=['tipo'=>'INTENSIVO','nivel'=>'MEDIA','titulo'=>'Intensivo termina el '.date('d/m',strtotime($r['fecha_fin'])),'detalle'=>'Revisar continuidad de participantes y reposiciones.','href'=>'/intensivo-detalle.php?id='.rawurlencode((string)$r['id']).'&sede='.rawurlencode($clave)];
if($s['minimo_mensual_socio']!==null){$periodo=$hoy->format('Y-m');[$yy,$mm]=array_map('intval',explode('-',$periodo));$d=$periodo.'-01';$h=$hoy->modify('last day of this month')->format('Y-m-d');$sql="SELECT COALESCE(SUM(CASE WHEN p.tipo='MENSUALIDAD' THEN p.importe*:pm WHEN p.tipo='INTENSIVO' THEN p.importe*:pi WHEN p.tipo='INSCRIPCION' THEN p.importe*:pins ELSE 0 END),0) FROM pagos p LEFT JOIN mensualidades m ON m.id=p.mensualidad_id LEFT JOIN cursos_intensivos ci ON ci.id=p.intensivo_id LEFT JOIN inscripciones i ON i.id=p.inscripcion_id WHERE p.estado='VALIDO' AND ((p.tipo='MENSUALIDAD' AND m.sede_id=:sm AND m.mes=:mes AND m.anio=:anio) OR (p.tipo='INTENSIVO' AND ci.sede_id=:sc AND ci.fecha_inicio BETWEEN :dc AND :hc) OR (p.tipo='INSCRIPCION' AND i.sede_id=:si AND i.fecha BETWEEN :di AND :hi))";$st=$pdo->prepare($sql);$st->execute([':pm'=>(float)$s['porcentaje_mensualidad_socio']/100,':pi'=>(float)$s['porcentaje_intensivo_socio']/100,':pins'=>(float)$s['porcentaje_inscripcion_socio']/100,':sm'=>$sid,':mes'=>$mm,':anio'=>$anio,':sc'=>$sid,':dc'=>$d,':hc'=>$h,':si'=>$sid,':di'=>$d,':hi'=>$h]);$a=(float)$st->fetchColumn();$min=(float)$s['minimo_mensual_socio'];$alertas[]=['tipo'=>'SOCIO','nivel'=>$a>=$min?'OK':'BAJA','titulo'=>$a>=$min?'Mínimo '.$s['socio'].' alcanzado ✓':'Mínimo '.$s['socio'].' en progreso','detalle'=>$a>=$min?'Las comisiones del próximo mes quedan habilitadas.':'Aporte actual: $'.number_format($a,0).' de $'.number_format($min,0).'.','href'=>'/reportes.php?periodo='.rawurlencode($periodo).'&sede='.rawurlencode($clave)];}out(['ok'=>true,'sede'=>$clave,'total'=>count($alertas),'alertas'=>$alertas]);}catch(Throwable$e){error_log('[alertas] '.$e->getMessage());out(['ok'=>false,'error'=>'No se pudieron cargar las alertas'],500);}
