<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
require_once __DIR__.'/../config/auth.php';
require_once __DIR__.'/../config/reglas-acceso.php';
require_once __DIR__.'/../config/telefono.php';
$config=require __DIR__.'/../config/database.php';
try{
$pdo=new PDO("mysql:host={$config['host']};dbname={$config['dbname']};charset={$config['charset']}",$config['user'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
$me=auth_require($_SERVER['REQUEST_METHOD']==='GET'?['ADMIN','VERIFICADOR']:['ADMIN']);$sedeClave=auth_active_sede_clave();$st=$pdo->prepare("SELECT id FROM sedes WHERE clave=:c AND activo=1 LIMIT 1");$st->execute([':c'=>$sedeClave]);$sedeId=(string)$st->fetchColumn();if($sedeId===''){http_response_code(422);echo json_encode(['ok'=>false,'error'=>'Sede activa inválida']);exit;}
if($_SERVER['REQUEST_METHOD']==='GET'){$st=$pdo->prepare("SELECT id,hora_inicio,hora_fin FROM horarios WHERE sede_id=:s AND activo=1 AND regular=1 ORDER BY hora_inicio");$st->execute([':s'=>$sedeId]);$horarios=$st->fetchAll();echo json_encode(['ok'=>true,'horarios'=>$horarios],JSON_UNESCAPED_UNICODE);exit;}
if($_SERVER['REQUEST_METHOD']!=='POST'){http_response_code(405);echo json_encode(['ok'=>false,'error'=>'Método no permitido']);exit;}
$in=json_decode(file_get_contents('php://input'),true);if(!is_array($in)){http_response_code(400);echo json_encode(['ok'=>false,'error'=>'JSON inválido'],JSON_UNESCAPED_UNICODE);exit;}$id=trim((string)($in['alumno_id']??''));$campo=strtoupper(trim((string)($in['campo']??'')));$valor=$in['valor']??null;
if($id===''||!in_array($campo,['WHATSAPP','HORARIO'],true)){http_response_code(422);echo json_encode(['ok'=>false,'error'=>'Datos inválidos']);exit;}
$st=$pdo->prepare("SELECT id FROM alumnos WHERE id=:id AND sede_id=:s LIMIT 1");$st->execute([':id'=>$id,':s'=>$sedeId]);if(!$st->fetchColumn()){http_response_code(404);echo json_encode(['ok'=>false,'error'=>'Alumno no encontrado en la sede activa']);exit;}
if($campo==='WHATSAPP'){$pais=strtoupper(trim((string)($in['whatsapp_pais']??'')));try{$v=telefono_normalizar_entrada(trim((string)$valor),$pais!==''?$pais:null);}catch(InvalidArgumentException $e){http_response_code(422);echo json_encode(['ok'=>false,'error'=>$e->getMessage()],JSON_UNESCAPED_UNICODE);exit;}$pdo->beginTransaction();regla_bloquear_identidades_alumnos($pdo);$st=$pdo->prepare("SELECT id FROM alumnos WHERE id=:id AND sede_id=:s LIMIT 1 FOR UPDATE");$st->execute([':id'=>$id,':s'=>$sedeId]);if(!$st->fetchColumn()){$pdo->rollBack();http_response_code(404);echo json_encode(['ok'=>false,'error'=>'Alumno no encontrado en la sede activa']);exit;}$st=$pdo->prepare("SELECT nombre FROM alumnos WHERE whatsapp=:v AND id<>:id LIMIT 1");$st->execute([':v'=>$v,':id'=>$id]);if($dup=$st->fetch()){$pdo->rollBack();http_response_code(409);echo json_encode(['ok'=>false,'error'=>'Ese WhatsApp ya pertenece a '.$dup['nombre']],JSON_UNESCAPED_UNICODE);exit;}$st=$pdo->prepare("UPDATE alumnos SET whatsapp=:v,updated_at=NOW() WHERE id=:id AND sede_id=:s");$st->execute([':v'=>$v,':id'=>$id,':s'=>$sedeId]);$pdo->commit();echo json_encode(['ok'=>true,'valor'=>$v],JSON_UNESCAPED_UNICODE);exit;}
$v=trim((string)$valor);if($v===''){http_response_code(422);echo json_encode(['ok'=>false,'error'=>'Selecciona un horario']);exit;}
$pdo->beginTransaction();
// Serializa el cambio con el alta a un intensivo. De otro modo ambos procesos
// podían validar el estado anterior y dejar un horario regular en un alumno
// que acababa de ingresar a un curso intensivo.
$st=$pdo->prepare("SELECT id FROM alumnos WHERE id=:id AND sede_id=:s LIMIT 1 FOR UPDATE");$st->execute([':id'=>$id,':s'=>$sedeId]);if(!$st->fetchColumn()){$pdo->rollBack();http_response_code(404);echo json_encode(['ok'=>false,'error'=>'Alumno no encontrado en la sede activa']);exit;}
$st=$pdo->prepare("SELECT 1 FROM curso_intensivo_alumnos cia INNER JOIN cursos_intensivos ci ON ci.id=cia.curso_intensivo_id WHERE cia.alumno_id=:a AND ci.sede_id=:s AND ci.estado IN ('PROGRAMADO','EN_CURSO') LIMIT 1");$st->execute([':a'=>$id,':s'=>$sedeId]);if($st->fetchColumn()){$pdo->rollBack();http_response_code(422);echo json_encode(['ok'=>false,'error'=>'El horario de un alumno en intensivo se modifica dentro del curso intensivo']);exit;}
$st=$pdo->prepare("SELECT id,hora_inicio,hora_fin FROM horarios WHERE id=:id AND sede_id=:s AND activo=1 AND regular=1 LIMIT 1 FOR UPDATE");$st->execute([':id'=>$v,':s'=>$sedeId]);$h=$st->fetch();if(!$h){$pdo->rollBack();http_response_code(422);echo json_encode(['ok'=>false,'error'=>'Horario no disponible en la sede activa']);exit;}
$st=$pdo->prepare("UPDATE alumnos SET horario_preferido_id=:h,updated_at=NOW() WHERE id=:id AND sede_id=:s");$st->execute([':h'=>$v,':id'=>$id,':s'=>$sedeId]);$pdo->commit();echo json_encode(['ok'=>true,'horario'=>$h],JSON_UNESCAPED_UNICODE);exit;
}catch(Throwable $e){if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();error_log('[alumno-rapido] '.$e->getMessage());http_response_code(500);echo json_encode(['ok'=>false,'error'=>'No se pudo actualizar el alumno'],JSON_UNESCAPED_UNICODE);}
