<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
require_once __DIR__.'/../config/auth.php';
$me=auth_require(['ADMIN']);
$config=require __DIR__.'/../config/database.php';
$pdo=new PDO("mysql:host={$config['host']};dbname={$config['dbname']};charset={$config['charset']}",$config['user'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
function out(array $d,int $c=200):never{http_response_code($c);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function siteId(PDO $pdo,string $clave):string{$st=$pdo->prepare("SELECT id FROM sedes WHERE clave=:c AND activo=1 LIMIT 1");$st->execute([':c'=>$clave]);$id=(string)$st->fetchColumn();if(!$id)out(['ok'=>false,'error'=>'Sede inválida'],422);return $id;}
try{
 if($_SERVER['REQUEST_METHOD']!=='POST')out(['ok'=>false,'error'=>'Método no permitido'],405);
 $in=json_decode(file_get_contents('php://input'),true);if(!is_array($in))out(['ok'=>false,'error'=>'Solicitud JSON inválida'],400);$nivel=strtoupper(trim((string)($in['nivel']??'')));$motivo=trim((string)($in['motivo']??''));$fecha=trim((string)($in['fecha']??''));$bloque=strtoupper(trim((string)($in['bloque']??'')));$claseId=trim((string)($in['clase_id']??''));$clave=auth_resolve_sede_clave((string)($in['sede']??'MONTEVERDE'));$sid=siteId($pdo,$clave);
 if(!in_array($nivel,['CLASE','SESION','JORNADA'],true))out(['ok'=>false,'error'=>'Nivel de cancelación inválido'],422);if($motivo==='')out(['ok'=>false,'error'=>'El motivo de cancelación es obligatorio'],422);if(mb_strlen($motivo)>500)out(['ok'=>false,'error'=>'El motivo no puede exceder 500 caracteres'],422);if($nivel==='CLASE'&&$claseId==='')out(['ok'=>false,'error'=>'Falta la clase'],422);if(in_array($nivel,['SESION','JORNADA'],true)){$date=DateTimeImmutable::createFromFormat('!Y-m-d',$fecha);if(!$date||$date->format('Y-m-d')!==$fecha)out(['ok'=>false,'error'=>'La fecha de la jornada no es válida'],422);}if($nivel==='SESION'&&!in_array($bloque,['AM','PM'],true))out(['ok'=>false,'error'=>'La sesión debe ser AM o PM'],422);
 $where='';$params=[':site'=>$sid];if($nivel==='CLASE'){$where='s.id=:id';$params[':id']=$claseId;}elseif($nivel==='SESION'){$where='s.fecha=:fecha AND s.bloque=:bloque';$params[':fecha']=$fecha;$params[':bloque']=$bloque;}else{$where='s.fecha=:fecha';$params[':fecha']=$fecha;}
 $st=$pdo->prepare("SELECT s.id,s.fecha,s.horario_id,s.bloque FROM sesiones s JOIN horarios h ON h.id=s.horario_id WHERE $where AND h.sede_id=:site AND s.estado<>'CANCELADA'");$st->execute($params);$clases=$st->fetchAll();if(!$clases)out(['ok'=>false,'error'=>'No hay clases activas que cancelar en esa selección'],422);
 $pdo->beginTransaction();$afectadas=0;$reposicionesIntensivo=0;foreach($clases as $clase){$u=$pdo->prepare("UPDATE sesiones SET estado='CANCELADA',motivo_cancelacion=:m,cerrada=1,fecha_cierre=NOW(),cerrada_por=:u WHERE id=:id AND estado<>'CANCELADA'");$u->execute([':m'=>$motivo,':u'=>$me['id'],':id'=>$clase['id']]);if(!$u->rowCount())continue;$afectadas++;if(!empty($clase['horario_id'])){$r=$pdo->prepare("UPDATE curso_intensivo_alumnos cia JOIN cursos_intensivos ci ON ci.id=cia.curso_intensivo_id SET cia.reposiciones_cancelacion=cia.reposiciones_cancelacion+1 WHERE cia.horario_id=:h AND ci.sede_id=:site AND ci.estado IN ('PROGRAMADO','EN_CURSO') AND :f BETWEEN ci.fecha_inicio AND ci.fecha_fin");$r->execute([':h'=>$clase['horario_id'],':site'=>$sid,':f'=>$clase['fecha']]);$reposicionesIntensivo+=$r->rowCount();}}
 $pdo->commit();out(['ok'=>true,'nivel'=>$nivel,'clases_canceladas'=>$afectadas,'reposiciones_intensivo_generadas'=>$reposicionesIntensivo,'mensaje'=>$nivel==='CLASE'?'Clase cancelada':($nivel==='SESION'?'Sesión cancelada':'Jornada cancelada')]);
}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();error_log('[cancelaciones-clases] '.$e->getMessage());out(['ok'=>false,'error'=>'No se pudo cancelar la selección de clases'],500);}
