<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
$config=require __DIR__.'/../config/database.php';require_once __DIR__.'/../config/auth.php';$user=auth_require(['ADMIN']);
$pdo=new PDO("mysql:host={$config['host']};dbname={$config['dbname']};charset={$config['charset']}",$config['user'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
function out(array $d,int $c=200):never{http_response_code($c);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function calc(PDO $pdo,string $periodo):array{$base=" FROM pagos p LEFT JOIN mensualidades m ON m.id=p.mensualidad_id LEFT JOIN cursos_intensivos ci ON ci.id=p.intensivo_id LEFT JOIN inscripciones i ON i.id=p.inscripcion_id ";$expr="CASE WHEN p.tipo='MENSUALIDAD' AND m.id IS NOT NULL THEN CONCAT(m.anio,'-',LPAD(m.mes,2,'0')) WHEN p.tipo='INTENSIVO' AND ci.id IS NOT NULL THEN DATE_FORMAT(ci.fecha_inicio,'%Y-%m') WHEN p.tipo='INSCRIPCION' AND i.id IS NOT NULL THEN DATE_FORMAT(i.fecha,'%Y-%m') ELSE DATE_FORMAT(p.fecha,'%Y-%m') END";$st=$pdo->prepare("SELECT COUNT(*) pagos,COALESCE(SUM(p.importe),0) total,COALESCE(SUM(CASE WHEN p.tipo='MENSUALIDAD' THEN p.importe ELSE 0 END),0) mens,COALESCE(SUM(CASE WHEN p.tipo='INSCRIPCION' THEN p.importe ELSE 0 END),0) ins,COALESCE(SUM(CASE WHEN p.tipo='INTENSIVO' THEN p.importe ELSE 0 END),0) ints {$base} WHERE p.estado='VALIDO' AND {$expr}=:periodo");$st->execute([':periodo'=>$periodo]);$r=$st->fetch();$min=(float)($pdo->query("SELECT valor FROM configuracion WHERE clave='minimo_proa_mensual' LIMIT 1")->fetchColumn()?:28000);$mens=(float)$r['mens'];$ints=(float)$r['ints'];$ins=(float)$r['ins'];$ha=$mens*.5+$ints*.5;$pr=$ha+$ins;return ['periodo'=>$periodo,'total'=>(float)$r['total'],'pagos'=>(int)$r['pagos'],'mensualidades'=>$mens,'inscripciones'=>$ins,'intensivos'=>$ints,'hache'=>$ha,'proa'=>$pr,'minimo'=>$min,'alcanzado'=>$pr>=$min];}
try{
 if($_SERVER['REQUEST_METHOD']==='GET'){$periodo=(string)($_GET['periodo']??date('Y-m'));$actual=calc($pdo,$periodo);$st=$pdo->prepare("SELECT c.*,u.usuario cerrado_por_usuario FROM cierres_mensuales c JOIN usuarios u ON u.id=c.cerrado_por WHERE c.periodo=:p LIMIT 1");$st->execute([':p'=>$periodo.'-01']);out(['ok'=>true,'actual'=>$actual,'cierre'=>$st->fetch()?:null]);}
 $in=json_decode(file_get_contents('php://input'),true);if(!is_array($in))out(['ok'=>false,'error'=>'JSON inválido'],400);$periodo=(string)($in['periodo']??'');if(!preg_match('/^\d{4}-\d{2}$/',$periodo))out(['ok'=>false,'error'=>'Periodo inválido'],422);$x=calc($pdo,$periodo);$st=$pdo->prepare("SELECT 1 FROM cierres_mensuales WHERE periodo=:p");$st->execute([':p'=>$periodo.'-01']);if($st->fetchColumn())out(['ok'=>false,'error'=>'Ese mes ya está cerrado. El cierre histórico no se sobrescribe.'],409);$st=$pdo->prepare("INSERT INTO cierres_mensuales(periodo,total_cobrado,mensualidades,inscripciones,intensivos,participacion_hache,participacion_proa,minimo_proa,minimo_alcanzado,total_pagos,observacion,cerrado_por) VALUES(:p,:t,:m,:i,:ci,:h,:pr,:min,:a,:n,:o,:u)");$st->execute([':p'=>$periodo.'-01',':t'=>$x['total'],':m'=>$x['mensualidades'],':i'=>$x['inscripciones'],':ci'=>$x['intensivos'],':h'=>$x['hache'],':pr'=>$x['proa'],':min'=>$x['minimo'],':a'=>$x['alcanzado']?1:0,':n'=>$x['pagos'],':o'=>trim((string)($in['observacion']??''))?:null,':u'=>$user['id']]);out(['ok'=>true,'mensaje'=>'Mes cerrado correctamente','cierre'=>$x],201);
}catch(Throwable $e){out(['ok'=>false,'error'=>$e->getMessage()],500);}
