<?php

declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
$config=require __DIR__.'/../config/database.php';
try{
$pdo=new PDO("mysql:host={$config['host']};dbname={$config['dbname']};charset={$config['charset']}",$config['user'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
$input=json_decode(file_get_contents('php://input'),true);if(!is_array($input)){http_response_code(400);echo json_encode(['ok'=>false,'error'=>'JSON inválido']);exit;}
$alumnoId=trim((string)($input['alumno_id']??''));$tipo=strtoupper(trim((string)($input['tipo']??'')));$importe=$input['importe']??null;$metodo=strtoupper(trim((string)($input['metodo']??'')));$fecha=trim((string)($input['fecha']??''));$observacion=trim((string)($input['observacion']??''));$createdBy=trim((string)($input['created_by']??''));$cursoId=trim((string)($input['curso_intensivo_id']??''));$cambiarPlanId=trim((string)($input['cambiar_plan_id']??''));
if($alumnoId===''||$fecha===''||$createdBy===''||!in_array($tipo,['INSCRIPCION','MENSUALIDAD','INTENSIVO'],true)||!is_numeric($importe)||(float)$importe<0||!in_array($metodo,['EFECTIVO','TRANSFERENCIA','MERCADO_PAGO'],true)){http_response_code(422);echo json_encode(['ok'=>false,'error'=>'Datos de pago incompletos o inválidos'],JSON_UNESCAPED_UNICODE);exit;}
$stmt=$pdo->prepare("SELECT id FROM usuarios WHERE id=:id LIMIT 1");$stmt->execute([':id'=>$createdBy]);if(!$stmt->fetch()){http_response_code(422);echo json_encode(['ok'=>false,'error'=>'Usuario administrativo inválido']);exit;}
$stmt=$pdo->prepare("SELECT a.id,a.nombre,a.plan_actual_id,a.horario_preferido_id,p.nombre plan_nombre,p.precio plan_precio FROM alumnos a LEFT JOIN planes p ON p.id=a.plan_actual_id WHERE a.id=:id LIMIT 1");$stmt->execute([':id'=>$alumnoId]);$alumno=$stmt->fetch();if(!$alumno){http_response_code(422);echo json_encode(['ok'=>false,'error'=>'Alumno no encontrado']);exit;}
try{$fechaPago=new DateTimeImmutable($fecha);}catch(Throwable $e){http_response_code(422);echo json_encode(['ok'=>false,'error'=>'Fecha inválida']);exit;}
$fechaSql=$fechaPago->format('Y-m-d H:i:s');$fechaDia=$fechaPago->format('Y-m-d');$mes=(int)$fechaPago->format('n');$anio=(int)$fechaPago->format('Y');$importeDecimal=number_format((float)$importe,2,'.','');
$pdo->beginTransaction();$inscripcionId=null;$mensualidadId=null;$intensivoId=null;

if($tipo==='INSCRIPCION'){
 $stmt=$pdo->prepare("SELECT p.fecha,p.folio FROM pagos p WHERE p.alumno_id=:id AND p.tipo='INSCRIPCION' AND p.estado='VALIDO' ORDER BY p.fecha DESC LIMIT 1");$stmt->execute([':id'=>$alumnoId]);$ult=$stmt->fetch();
 if($ult){$u=new DateTimeImmutable(substr($ult['fecha'],0,10));$permitida=$u->modify('first day of this month')->modify('+3 months');if($fechaPago<$permitida){throw new RuntimeException('No corresponde nueva inscripción todavía. Próxima fecha posible: '.$permitida->format('d/m/Y'));}}
 $inscripcionId=$pdo->query("SELECT UUID()")->fetchColumn();$stmt=$pdo->prepare("INSERT INTO inscripciones(id,alumno_id,fecha,origen,importe,observacion,created_by) VALUES(:id,:alumno,:fecha,'REGULAR',:importe,:obs,:uid)");$stmt->execute([':id'=>$inscripcionId,':alumno'=>$alumnoId,':fecha'=>$fechaDia,':importe'=>$importeDecimal,':obs'=>$observacion!==''?$observacion:null,':uid'=>$createdBy]);
}
elseif($tipo==='MENSUALIDAD'){
 $stmt=$pdo->prepare("SELECT id,estado FROM mensualidades WHERE alumno_id=:id AND mes=:mes AND anio=:anio LIMIT 1");$stmt->execute([':id'=>$alumnoId,':mes'=>$mes,':anio'=>$anio]);$exist=$stmt->fetch();if($exist&&$exist['estado']==='PAGADA')throw new RuntimeException('La mensualidad de este mes ya está pagada');
 if($cambiarPlanId!==''){$stmt=$pdo->prepare("SELECT id,nombre,precio FROM planes WHERE id=:id AND activo=1 LIMIT 1");$stmt->execute([':id'=>$cambiarPlanId]);$nuevo=$stmt->fetch();if(!$nuevo)throw new RuntimeException('El plan seleccionado no está disponible');if(abs((float)$nuevo['precio']-(float)$importe)>0.009)throw new RuntimeException('El importe no coincide con el plan seleccionado');$stmt=$pdo->prepare("UPDATE alumnos SET plan_actual_id=:plan,updated_at=NOW() WHERE id=:alumno");$stmt->execute([':plan'=>$cambiarPlanId,':alumno'=>$alumnoId]);$alumno['plan_actual_id']=$cambiarPlanId;$alumno['plan_nombre']=$nuevo['nombre'];$alumno['plan_precio']=$nuevo['precio'];}
 if(empty($alumno['plan_actual_id']))throw new RuntimeException('El alumno no tiene un plan activo');
 $estandar=number_format((float)$alumno['plan_precio'],2,'.','');if((float)$importeDecimal!==(float)$estandar&&$observacion==='')throw new RuntimeException('El importe es distinto al plan actual; agrega una observación o confirma el cambio de plan');
 if($exist){$mensualidadId=$exist['id'];$stmt=$pdo->prepare("UPDATE mensualidades SET plan_id=:plan,importe_estandar=:est,importe_a_cobrar=:cob,importe_cobrado=:cob,estado='PAGADA',fecha_pago=:fecha,observacion=:obs,updated_at=NOW() WHERE id=:id");$stmt->execute([':plan'=>$alumno['plan_actual_id'],':est'=>$estandar,':cob'=>$importeDecimal,':fecha'=>$fechaSql,':obs'=>$observacion!==''?$observacion:null,':id'=>$mensualidadId]);}
 else{$mensualidadId=$pdo->query("SELECT UUID()")->fetchColumn();$stmt=$pdo->prepare("INSERT INTO mensualidades(id,alumno_id,mes,anio,plan_id,importe_estandar,importe_a_cobrar,importe_cobrado,estado,observacion,fecha_pago,created_by) VALUES(:id,:alumno,:mes,:anio,:plan,:est,:cob,:cob,'PAGADA',:obs,:fecha,:uid)");$stmt->execute([':id'=>$mensualidadId,':alumno'=>$alumnoId,':mes'=>$mes,':anio'=>$anio,':plan'=>$alumno['plan_actual_id'],':est'=>$estandar,':cob'=>$importeDecimal,':obs'=>$observacion!==''?$observacion:null,':fecha'=>$fechaSql,':uid'=>$createdBy]);}
}
else{
 if($cursoId!==''){$stmt=$pdo->prepare("SELECT ci.id FROM curso_intensivo_alumnos cia INNER JOIN cursos_intensivos ci ON ci.id=cia.curso_intensivo_id WHERE cia.alumno_id=:alumno AND ci.id=:curso AND ci.estado IN ('PROGRAMADO','EN_CURSO') LIMIT 1");$stmt->execute([':alumno'=>$alumnoId,':curso'=>$cursoId]);}else{$stmt=$pdo->prepare("SELECT ci.id FROM curso_intensivo_alumnos cia INNER JOIN cursos_intensivos ci ON ci.id=cia.curso_intensivo_id WHERE cia.alumno_id=:alumno AND ci.estado IN ('PROGRAMADO','EN_CURSO') ORDER BY ci.fecha_inicio DESC LIMIT 1");$stmt->execute([':alumno'=>$alumnoId]);}$curso=$stmt->fetch();if(!$curso)throw new RuntimeException('El alumno no está inscrito en un intensivo activo');$intensivoId=$curso['id'];$stmt=$pdo->prepare("SELECT id FROM pagos WHERE intensivo_id=:curso AND alumno_id=:alumno AND tipo='INTENSIVO' AND estado='VALIDO' LIMIT 1");$stmt->execute([':curso'=>$intensivoId,':alumno'=>$alumnoId]);if($stmt->fetch())throw new RuntimeException('Este alumno ya pagó este curso intensivo');
}

$stmt=$pdo->prepare("INSERT INTO pagos(alumno_id,inscripcion_id,mensualidad_id,intensivo_id,tipo,importe,metodo,fecha,estado,observacion,created_by) VALUES(:alumno,:ins,:men,:int,:tipo,:importe,:metodo,:fecha,'VALIDO',:obs,:uid)");$stmt->execute([':alumno'=>$alumnoId,':ins'=>$inscripcionId,':men'=>$mensualidadId,':int'=>$intensivoId,':tipo'=>$tipo,':importe'=>$importeDecimal,':metodo'=>$metodo,':fecha'=>$fechaSql,':obs'=>$observacion!==''?$observacion:null,':uid'=>$createdBy]);$folio=(int)$pdo->lastInsertId();$pdo->commit();
$stmt=$pdo->prepare("SELECT p.*,a.nombre alumno_nombre FROM pagos p INNER JOIN alumnos a ON a.id=p.alumno_id WHERE p.folio=:folio LIMIT 1");$stmt->execute([':folio'=>$folio]);echo json_encode(['ok'=>true,'mensaje'=>'Pago registrado correctamente','pago'=>$stmt->fetch()],JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT);
}catch(Throwable $e){if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();http_response_code(422);echo json_encode(['ok'=>false,'error'=>$e->getMessage()],JSON_UNESCAPED_UNICODE);}
