<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
require_once __DIR__.'/../config/auth.php';
require_once __DIR__.'/../config/telefono.php';
require_once __DIR__.'/../config/reglas-acceso.php';
$me=auth_require(['ALUMNO']);
$config=require __DIR__.'/../config/database.php';
$pdo=new PDO("mysql:host={$config['host']};dbname={$config['dbname']};charset={$config['charset']}",$config['user'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
function out(array $d,int $c=200):never{http_response_code($c);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
$aid=(string)$me['alumno_id'];
try{
 if($_SERVER['REQUEST_METHOD']==='GET'){
  $st=$pdo->prepare("SELECT a.id,a.sede_id,a.nombre,a.whatsapp,a.correo,a.estado_administrativo,p.nombre plan_nombre,p.sesiones_semana,p.precio,h.hora_inicio,h.hora_fin,EXISTS(SELECT 1 FROM curso_intensivo_alumnos cia JOIN cursos_intensivos ci ON ci.id=cia.curso_intensivo_id WHERE cia.alumno_id=a.id AND ci.sede_id=a.sede_id AND ci.estado IN ('PROGRAMADO','EN_CURSO')) intensivo_activo FROM alumnos a LEFT JOIN planes p ON p.id=a.plan_actual_id AND p.sede_id=a.sede_id LEFT JOIN horarios h ON h.id=a.horario_preferido_id AND h.sede_id=a.sede_id WHERE a.id=:id LIMIT 1");$st->execute([':id'=>$aid]);$alumno=$st->fetch();if(!$alumno)out(['ok'=>false,'error'=>'Alumno no encontrado'],404);$sedeId=(string)$alumno['sede_id'];unset($alumno['sede_id']);
  $st=$pdo->prepare("SELECT folio,tipo,importe,metodo,fecha,estado,observacion FROM pagos WHERE alumno_id=:a ORDER BY fecha DESC,folio DESC LIMIT 24");$st->execute([':a'=>$aid]);$pagos=$st->fetchAll();
  $st=$pdo->prepare("SELECT id,fecha_desde,fecha_hasta,motivo,estado,created_at FROM avisos_ausencia WHERE alumno_id=:a ORDER BY fecha_desde DESC,created_at DESC LIMIT 24");$st->execute([':a'=>$aid]);$avisos=$st->fetchAll();
  $st=$pdo->prepare("SELECT rr.id,rr.estado,rr.created_at,rr.used_at,se.fecha fecha_ausencia FROM reposiciones_regulares rr JOIN asistencias aa ON aa.id=rr.ausencia_asistencia_id JOIN sesiones se ON se.id=aa.sesion_id JOIN horarios h ON h.id=se.horario_id WHERE rr.alumno_id=:a AND h.sede_id=:sede ORDER BY se.fecha DESC");$st->execute([':a'=>$aid,':sede'=>$sedeId]);$repos=$st->fetchAll();
  $st=$pdo->prepare("SELECT ci.id,ci.fecha_inicio,ci.fecha_fin,ci.estado,cia.reposiciones_justificadas,cia.reposiciones_cancelacion,h.hora_inicio,h.hora_fin FROM curso_intensivo_alumnos cia JOIN cursos_intensivos ci ON ci.id=cia.curso_intensivo_id LEFT JOIN horarios h ON h.id=cia.horario_id AND h.sede_id=ci.sede_id WHERE cia.alumno_id=:a AND ci.sede_id=:sede ORDER BY ci.fecha_inicio DESC LIMIT 6");$st->execute([':a'=>$aid,':sede'=>$sedeId]);$intensivos=$st->fetchAll();
  $st=$pdo->prepare("SELECT id,titulo,cuerpo,audiencia,vigencia_desde,vigencia_hasta,created_at FROM mensajes WHERE sede_id=:sede AND activo=1 AND (vigencia_desde IS NULL OR vigencia_desde<=CURDATE()) AND (vigencia_hasta IS NULL OR vigencia_hasta>=CURDATE()) AND (audiencia='TODOS' OR (audiencia='ALUMNO' AND alumno_id=:a) OR (audiencia='REGULARES' AND :i1=0) OR (audiencia='INTENSIVOS' AND :i2=1)) ORDER BY created_at DESC LIMIT 20");$st->execute([':sede'=>$sedeId,':a'=>$aid,':i1'=>(int)$alumno['intensivo_activo'],':i2'=>(int)$alumno['intensivo_activo']]);$mensajes=$st->fetchAll();
  out(['ok'=>true,'alumno'=>$alumno,'pagos'=>$pagos,'avisos'=>$avisos,'reposiciones'=>$repos,'intensivos'=>$intensivos,'mensajes'=>$mensajes]);
 }
 if($_SERVER['REQUEST_METHOD']!=='POST')out(['ok'=>false,'error'=>'Método no permitido'],405);
 $in=json_decode(file_get_contents('php://input'),true);if(!is_array($in))out(['ok'=>false,'error'=>'JSON inválido'],400);$accion=strtoupper((string)($in['accion']??''));
 if($accion==='AVISO'){$desde=(string)($in['fecha_desde']??'');$hasta=(string)($in['fecha_hasta']??$desde);$motivo=trim((string)($in['motivo']??''));if(!$desde||!$hasta||$motivo==='')out(['ok'=>false,'error'=>'Completa las fechas y el motivo'],422);$d=DateTimeImmutable::createFromFormat('!Y-m-d',$desde);$h=DateTimeImmutable::createFromFormat('!Y-m-d',$hasta);if(!$d||!$h||$d->format('Y-m-d')!==$desde||$h->format('Y-m-d')!==$hasta)out(['ok'=>false,'error'=>'Las fechas no son válidas'],422);if($h<$d)out(['ok'=>false,'error'=>'La fecha final no puede ser anterior a la inicial'],422);if($h<new DateTimeImmutable('today'))out(['ok'=>false,'error'=>'El aviso debe corresponder a una fecha actual o futura'],422);if(mb_strlen($motivo)>500)out(['ok'=>false,'error'=>'El motivo no puede exceder 500 caracteres'],422);$pdo->beginTransaction();$st=$pdo->prepare("SELECT id FROM alumnos WHERE id=:a LIMIT 1 FOR UPDATE");$st->execute([':a'=>$aid]);if(!$st->fetchColumn()){$pdo->rollBack();out(['ok'=>false,'error'=>'Alumno no encontrado'],404);}$st=$pdo->prepare("SELECT 1 FROM avisos_ausencia WHERE alumno_id=:a AND fecha_desde=:d AND fecha_hasta=:h AND estado='ACTIVO' LIMIT 1");$st->execute([':a'=>$aid,':d'=>$desde,':h'=>$hasta]);if($st->fetchColumn()){$pdo->rollBack();out(['ok'=>false,'error'=>'Ya existe un aviso activo para ese mismo rango'],409);}$id=(string)$pdo->query("SELECT UUID()")->fetchColumn();$st=$pdo->prepare("INSERT INTO avisos_ausencia(id,alumno_id,fecha_desde,fecha_hasta,motivo,estado,created_by) VALUES(:id,:a,:d,:h,:m,'ACTIVO',:u)");$st->execute([':id'=>$id,':a'=>$aid,':d'=>$desde,':h'=>$hasta,':m'=>$motivo,':u'=>$me['id']]);$pdo->commit();out(['ok'=>true,'id'=>$id]);}
 if($accion==='CANCELAR_AVISO'){$id=(string)($in['id']??'');if($id==='')out(['ok'=>false,'error'=>'Aviso inválido'],422);$st=$pdo->prepare("UPDATE avisos_ausencia SET estado='CANCELADO' WHERE id=:id AND alumno_id=:a AND estado='ACTIVO'");$st->execute([':id'=>$id,':a'=>$aid]);if($st->rowCount()===0)out(['ok'=>false,'error'=>'Aviso activo no encontrado'],404);out(['ok'=>true]);}
 if($accion==='PERFIL'){$pais=strtoupper(trim((string)($in['whatsapp_pais']??'')));try{$wa=telefono_normalizar_entrada(trim((string)($in['whatsapp']??'')),$pais!==''?$pais:null);}catch(InvalidArgumentException $e){out(['ok'=>false,'error'=>$e->getMessage()],422);}$correo=trim((string)($in['correo']??''));if($correo!==''&&!filter_var($correo,FILTER_VALIDATE_EMAIL))out(['ok'=>false,'error'=>'El correo no es válido'],422);$pdo->beginTransaction();regla_bloquear_identidades_alumnos($pdo);$st=$pdo->prepare("SELECT nombre FROM alumnos WHERE whatsapp=:w AND id<>:a LIMIT 1");$st->execute([':w'=>$wa,':a'=>$aid]);if($dup=$st->fetch()){$pdo->rollBack();out(['ok'=>false,'error'=>'Ese WhatsApp ya pertenece a '.$dup['nombre']],409);}$st=$pdo->prepare("UPDATE alumnos SET whatsapp=:w,correo=:c,updated_at=NOW() WHERE id=:a");$st->execute([':w'=>$wa,':c'=>$correo?:null,':a'=>$aid]);$pdo->commit();out(['ok'=>true]);}
 out(['ok'=>false,'error'=>'Acción inválida'],422);
}catch(Throwable $e){if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();error_log('[portal-alumno] '.$e->getMessage());out(['ok'=>false,'error'=>'No se pudo procesar la solicitud'],500);}
