<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
require_once __DIR__.'/../config/auth.php';
auth_require(['ADMIN','VERIFICADOR']);
$config=require __DIR__.'/../config/database.php';
try{
$pdo=new PDO("mysql:host={$config['host']};dbname={$config['dbname']};charset={$config['charset']}",$config['user'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
function out(array $d,int $code=200):never{http_response_code($code);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function getSede(PDO $pdo,string $clave):array{$st=$pdo->prepare("SELECT * FROM sedes WHERE clave=:c AND activo=1 LIMIT 1");$st->execute([':c'=>$clave]);$s=$st->fetch();if(!$s)out(['ok'=>false,'error'=>'Sede inválida'],422);return $s;}
$periodo=(string)($_GET['periodo']??date('Y-m'));if(!preg_match('/^\d{4}-\d{2}$/',$periodo))$periodo=date('Y-m');
$sedeClave=auth_resolve_sede_clave((string)($_GET['sede']??'MONTEVERDE'));$sede=getSede($pdo,$sedeClave);$sedeId=$sede['id'];
[$anio,$mes]=array_map('intval',explode('-',$periodo));$desde=$periodo.'-01';$hasta=(new DateTimeImmutable($desde))->modify('last day of this month')->format('Y-m-d');
$sql="SELECT COUNT(*) pagos_count,COALESCE(SUM(p.importe),0) total,COALESCE(SUM(p.tipo='INSCRIPCION'),0) inscripciones_count,COALESCE(SUM(CASE WHEN p.tipo='INSCRIPCION' THEN p.importe ELSE 0 END),0) inscripciones_total,COALESCE(SUM(p.tipo='MENSUALIDAD'),0) mensualidades_count,COALESCE(SUM(CASE WHEN p.tipo='MENSUALIDAD' THEN p.importe ELSE 0 END),0) mensualidades_total,COALESCE(SUM(p.tipo='INTENSIVO'),0) intensivos_count,COALESCE(SUM(CASE WHEN p.tipo='INTENSIVO' THEN p.importe ELSE 0 END),0) intensivos_total FROM pagos p LEFT JOIN mensualidades m ON m.id=p.mensualidad_id LEFT JOIN inscripciones i ON i.id=p.inscripcion_id LEFT JOIN cursos_intensivos ci ON ci.id=p.intensivo_id WHERE p.estado='VALIDO' AND ((p.tipo='MENSUALIDAD' AND m.sede_id=:sm AND m.mes=:mes AND m.anio=:anio) OR (p.tipo='INSCRIPCION' AND i.sede_id=:si AND i.fecha BETWEEN :di AND :hi) OR (p.tipo='INTENSIVO' AND ci.sede_id=:sc AND ci.fecha_inicio BETWEEN :dc AND :hc))";
$params=[':sm'=>$sedeId,':mes'=>$mes,':anio'=>$anio,':si'=>$sedeId,':di'=>$desde,':hi'=>$hasta,':sc'=>$sedeId,':dc'=>$desde,':hc'=>$hasta];$st=$pdo->prepare($sql);$st->execute($params);$fin=$st->fetch();
$mens=(float)$fin['mensualidades_total'];$int=(float)$fin['intensivos_total'];$ins=(float)$fin['inscripciones_total'];$pm=(float)$sede['porcentaje_mensualidad_socio']/100;$pi=(float)$sede['porcentaje_intensivo_socio']/100;$pins=(float)$sede['porcentaje_inscripcion_socio']/100;
$socio=($mens*$pm)+($int*$pi)+($ins*$pins);$hache=($mens*(1-$pm))+($int*(1-$pi))+($ins*(1-$pins));$minimo=$sede['minimo_mensual_socio']!==null?(float)$sede['minimo_mensual_socio']:0.0;$faltante=$minimo>0?max(0,$minimo-$socio):0;$alcanzado=$minimo>0?$socio>=$minimo:null;$progreso=$minimo>0?min(100,round(($socio/$minimo)*100,1)):null;
$inicioHist=(new DateTimeImmutable($desde))->modify('-11 months');$meses=[];for($d=$inicioHist;$d<=new DateTimeImmutable($desde);$d=$d->modify('+1 month')){$p=$d->format('Y-m');[$yy,$mm]=array_map('intval',explode('-',$p));$di=$p.'-01';$ha=(new DateTimeImmutable($di))->modify('last day of this month')->format('Y-m-d');$q=$pdo->prepare($sql);$q->execute([':sm'=>$sedeId,':mes'=>$mm,':anio'=>$yy,':si'=>$sedeId,':di'=>$di,':hi'=>$ha,':sc'=>$sedeId,':dc'=>$di,':hc'=>$ha]);$r=$q->fetch();if((int)$r['pagos_count']===0)continue;$m=(float)$r['mensualidades_total'];$ii=(float)$r['intensivos_total'];$is=(float)$r['inscripciones_total'];$soc=$m*$pm+$ii*$pi+$is*$pins;$hac=$m*(1-$pm)+$ii*(1-$pi)+$is*(1-$pins);$meses[]=['periodo'=>$p,'movimientos'=>(int)$r['pagos_count'],'total'=>(float)$r['total'],'inscripciones'=>$is,'mensualidades'=>$m,'intensivos'=>$ii,'hache'=>$hac,'proa'=>$soc,'socio'=>$soc,'minimo_alcanzado'=>$minimo>0?$soc>=$minimo:null];}
$st=$pdo->prepare("SELECT COUNT(DISTINCT a.alumno_id) alumnos_con_asistencia,COALESCE(SUM(a.estado='PRESENTE'),0) presentes,COALESCE(SUM(a.estado='AUSENTE_JUSTIFICADA'),0) justificadas,COALESCE(SUM(a.estado='AUSENTE_NO_JUSTIFICADA'),0) no_justificadas FROM asistencias a JOIN sesiones ss ON ss.id=a.sesion_id JOIN alumnos al ON al.id=a.alumno_id WHERE ss.fecha BETWEEN :d AND :h AND al.sede_id=:s");$st->execute([':d'=>$desde,':h'=>$hasta,':s'=>$sedeId]);$asis=$st->fetch();
out(['ok'=>true,'periodo'=>$periodo,'sede'=>['clave'=>$sede['clave'],'nombre'=>$sede['nombre'],'socio'=>$sede['socio']],'desde'=>$desde,'hasta'=>$hasta,'finanzas'=>$fin,'convenio_proa'=>['hache'=>$hache,'proa'=>$socio,'socio'=>$socio,'socio_nombre'=>$sede['socio'],'minimo'=>$minimo,'faltante'=>$faltante,'alcanzado'=>$alcanzado,'progreso'=>$progreso,'porcentajes'=>['mensualidades'=>(float)$sede['porcentaje_mensualidad_socio'],'intensivos'=>(float)$sede['porcentaje_intensivo_socio'],'inscripciones'=>(float)$sede['porcentaje_inscripcion_socio']]],'meses'=>array_reverse($meses),'asistencia'=>$asis]);
}catch(Throwable $e){out(['ok'=>false,'error'=>$e->getMessage()],500);}
