<?php
declare(strict_types=1);
$config=require __DIR__.'/../config/database.php';
$pdo=new PDO("mysql:host={$config['host']};dbname={$config['dbname']};charset={$config['charset']}",$config['user'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
$desde=(string)($_GET['desde']??date('Y-m-01'));$hasta=(string)($_GET['hasta']??date('Y-m-t'));if($hasta<$desde){[$desde,$hasta]=[$hasta,$desde];}$clave=strtoupper(trim((string)($_GET['sede']??'MONTEVERDE')));$st=$pdo->prepare("SELECT id,nombre FROM sedes WHERE clave=:c AND activo=1 LIMIT 1");$st->execute([':c'=>$clave]);$s=$st->fetch();if(!$s){http_response_code(422);exit('Sede inválida');}
$periodoDesde=substr($desde,0,7);$periodoHasta=substr($hasta,0,7);
header('Content-Type: text/csv; charset=utf-8');header('Content-Disposition: attachment; filename="hache-reporte-'.strtolower($clave).'-'.$desde.'-'.$hasta.'.csv"');echo "\xEF\xBB\xBF";$out=fopen('php://output','w');fputcsv($out,['Sede','Folio','Alumno','Tipo','Importe','Método','Fecha real de pago','Periodo económico','Estado']);
$sql="SELECT :sede_nombre sede,p.folio,a.nombre,p.tipo,p.importe,p.metodo,p.fecha,CASE WHEN p.tipo='MENSUALIDAD' AND m.id IS NOT NULL THEN CONCAT(m.anio,'-',LPAD(m.mes,2,'0')) WHEN p.tipo='INTENSIVO' AND ci.id IS NOT NULL THEN DATE_FORMAT(ci.fecha_inicio,'%Y-%m') WHEN p.tipo='INSCRIPCION' AND i.id IS NOT NULL THEN DATE_FORMAT(i.fecha,'%Y-%m') ELSE DATE_FORMAT(p.fecha,'%Y-%m') END periodo,p.estado FROM pagos p JOIN alumnos a ON a.id=p.alumno_id LEFT JOIN mensualidades m ON m.id=p.mensualidad_id LEFT JOIN cursos_intensivos ci ON ci.id=p.intensivo_id LEFT JOIN inscripciones i ON i.id=p.inscripcion_id WHERE ((p.tipo='MENSUALIDAD' AND m.sede_id=:s AND CONCAT(m.anio,'-',LPAD(m.mes,2,'0')) BETWEEN :pd AND :ph) OR (p.tipo='INTENSIVO' AND ci.sede_id=:s AND DATE_FORMAT(ci.fecha_inicio,'%Y-%m') BETWEEN :pd AND :ph) OR (p.tipo='INSCRIPCION' AND i.sede_id=:s AND DATE_FORMAT(i.fecha,'%Y-%m') BETWEEN :pd AND :ph)) ORDER BY periodo,p.fecha,p.folio";
$st=$pdo->prepare($sql);$st->execute([':sede_nombre'=>$s['nombre'],':s'=>$s['id'],':pd'=>$periodoDesde,':ph'=>$periodoHasta]);foreach($st as $r)fputcsv($out,$r);fclose($out);
