<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
$config=require __DIR__.'/../config/database.php';
function jsonOut(array $data,int $status=200):never{http_response_code($status);echo json_encode($data,JSON_UNESCAPED_UNICODE|JSON_PRETTY_PRINT);exit;}
function site(PDO $pdo,string $clave):array{$st=$pdo->prepare("SELECT id,clave,nombre FROM sedes WHERE clave=:c AND activo=1 LIMIT 1");$st->execute([':c'=>$clave]);$s=$st->fetch();if(!$s)jsonOut(['ok'=>false,'error'=>'Sede inválida'],422);return $s;}
function monthData(PDO $pdo,int $mes,int $anio,string $sedeId):array{
    $inicio=sprintf('%04d-%02d-01',$anio,$mes);$fin=(new DateTimeImmutable($inicio))->modify('+1 month')->format('Y-m-d');
    $stmt=$pdo->prepare("SELECT COUNT(*) alumnos,SUM(COALESCE(importe_cobrado,0)) total FROM mensualidades WHERE sede_id=:s AND mes=:mes AND anio=:anio AND estado='PAGADA'");$stmt->execute([':s'=>$sedeId,':mes'=>$mes,':anio'=>$anio]);$mp=$stmt->fetch();
    $where="p.estado='VALIDO' AND ((p.tipo='MENSUALIDAD' AND m.sede_id=:s_m AND m.mes=:mes AND m.anio=:anio) OR (p.tipo='INSCRIPCION' AND i.sede_id=:s_i AND i.fecha>=:inicio_i AND i.fecha<:fin_i) OR (p.tipo='INTENSIVO' AND ci.sede_id=:s_ci AND ci.fecha_inicio>=:inicio_ci AND ci.fecha_inicio<:fin_ci))";
    $params=[':s_m'=>$sedeId,':mes'=>$mes,':anio'=>$anio,':s_i'=>$sedeId,':inicio_i'=>$inicio,':fin_i'=>$fin,':s_ci'=>$sedeId,':inicio_ci'=>$inicio,':fin_ci'=>$fin];
    $joins=" FROM pagos p LEFT JOIN mensualidades m ON m.id=p.mensualidad_id LEFT JOIN inscripciones i ON i.id=p.inscripcion_id LEFT JOIN cursos_intensivos ci ON ci.id=p.intensivo_id ";
    $stmt=$pdo->prepare("SELECT p.tipo,COUNT(*) cantidad,COUNT(DISTINCT p.alumno_id) alumnos,SUM(p.importe) total".$joins."WHERE ".$where." GROUP BY p.tipo");$stmt->execute($params);
    $porTipo=['INSCRIPCION'=>['cantidad'=>0,'alumnos'=>0,'total'=>0.0],'MENSUALIDAD'=>['cantidad'=>0,'alumnos'=>0,'total'=>0.0],'INTENSIVO'=>['cantidad'=>0,'alumnos'=>0,'total'=>0.0]];foreach($stmt->fetchAll() as $r)$porTipo[$r['tipo']]=['cantidad'=>(int)$r['cantidad'],'alumnos'=>(int)$r['alumnos'],'total'=>(float)$r['total']];
    $stmt=$pdo->prepare("SELECT p.metodo,COUNT(*) cantidad,SUM(p.importe) total".$joins."WHERE ".$where." GROUP BY p.metodo ORDER BY total DESC");$stmt->execute($params);$metodos=[];foreach($stmt->fetchAll() as $r)$metodos[]=['metodo'=>$r['metodo'],'cantidad'=>(int)$r['cantidad'],'total'=>(float)$r['total']];
    $stmt=$pdo->prepare("SELECT COUNT(*) cantidad,COUNT(DISTINCT p.alumno_id) alumnos,SUM(p.importe) total".$joins."WHERE ".$where);$stmt->execute($params);$caja=$stmt->fetch();
    return ['periodo'=>['mes'=>$mes,'anio'=>$anio],'mensualidades_periodo'=>['alumnos'=>(int)($mp['alumnos']??0),'total'=>(float)($mp['total']??0)],'caja'=>['cantidad'=>(int)($caja['cantidad']??0),'alumnos'=>(int)($caja['alumnos']??0),'total'=>(float)($caja['total']??0)],'por_tipo'=>$porTipo,'metodos'=>$metodos];
}
try{
 $pdo=new PDO("mysql:host={$config['host']};dbname={$config['dbname']};charset={$config['charset']}",$config['user'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
 $clave=strtoupper(trim((string)($_GET['sede']??'MONTEVERDE')));$s=site($pdo,$clave);
 if(isset($_GET['desde'],$_GET['hasta'])){if(!preg_match('/^\d{4}-\d{2}$/',(string)$_GET['desde'])||!preg_match('/^\d{4}-\d{2}$/',(string)$_GET['hasta']))jsonOut(['ok'=>false,'error'=>'Rango inválido'],422);$desde=new DateTimeImmutable($_GET['desde'].'-01');$hasta=new DateTimeImmutable($_GET['hasta'].'-01');if($desde>$hasta)jsonOut(['ok'=>false,'error'=>'El periodo inicial no puede ser posterior al final'],422);$diff=((int)$hasta->format('Y')-(int)$desde->format('Y'))*12+((int)$hasta->format('n')-(int)$desde->format('n'));if($diff>59)jsonOut(['ok'=>false,'error'=>'El historial admite un máximo de 60 meses por consulta'],422);$meses=[];$tot=['caja'=>0.0,'pagos'=>0,'inscripciones'=>0.0,'mensualidades'=>0.0,'intensivos'=>0.0,'mensualidades_periodo'=>0.0];for($d=$desde;$d<=$hasta;$d=$d->modify('+1 month')){$x=monthData($pdo,(int)$d->format('n'),(int)$d->format('Y'),$s['id']);$meses[]=$x;$tot['caja']+=$x['caja']['total'];$tot['pagos']+=$x['caja']['cantidad'];$tot['inscripciones']+=$x['por_tipo']['INSCRIPCION']['total'];$tot['mensualidades']+=$x['por_tipo']['MENSUALIDAD']['total'];$tot['intensivos']+=$x['por_tipo']['INTENSIVO']['total'];$tot['mensualidades_periodo']+=$x['mensualidades_periodo']['total'];}jsonOut(['ok'=>true,'sede'=>$s,'rango'=>['desde'=>$_GET['desde'],'hasta'=>$_GET['hasta'],'meses'=>count($meses)],'totales'=>$tot,'detalle'=>$meses]);}
 $mes=(int)($_GET['mes']??date('n'));$anio=(int)($_GET['anio']??date('Y'));if($mes<1||$mes>12||$anio<2000||$anio>2100)jsonOut(['ok'=>false,'error'=>'Periodo inválido'],422);jsonOut(['ok'=>true,'sede'=>$s]+monthData($pdo,$mes,$anio,$s['id']));
}catch(Throwable $e){jsonOut(['ok'=>false,'error'=>$e->getMessage()],500);}
