<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
require_once __DIR__.'/../config/auth.php';
require_once __DIR__.'/../config/reglas-acceso.php';
$config=require __DIR__.'/../config/database.php';
$pdo=new PDO("mysql:host={$config['host']};dbname={$config['dbname']};charset={$config['charset']}",$config['user'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
function out(array $d,int $c=200):never{http_response_code($c);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function siteId(PDO $pdo,string $clave):string{$st=$pdo->prepare("SELECT id FROM sedes WHERE clave=:c AND activo=1 LIMIT 1");$st->execute([':c'=>$clave]);$id=(string)$st->fetchColumn();if(!$id)out(['ok'=>false,'error'=>'Sede inválida'],422);return $id;}
function fechaLaborable(string $fecha):DateTimeImmutable{$d=DateTimeImmutable::createFromFormat('!Y-m-d',$fecha);if(!$d||$d->format('Y-m-d')!==$fecha)out(['ok'=>false,'error'=>'Fecha inválida'],422);if((int)$d->format('N')>=6)out(['ok'=>false,'error'=>'Las sesiones solo pueden generarse de lunes a viernes'],422);return $d;}
function generarSesiones(PDO $pdo,string $fecha,string $uid,string $sedeId):int{
 $sql="SELECT DISTINCT h.id,h.hora_inicio FROM horarios h WHERE h.sede_id=:s AND h.activo=1 AND (EXISTS(SELECT 1 FROM alumnos a WHERE a.sede_id=:sa AND a.horario_preferido_id=h.id AND a.estado_administrativo IN ('ACTIVO','PENDIENTE')) OR EXISTS(SELECT 1 FROM curso_intensivo_alumnos cia JOIN cursos_intensivos ci ON ci.id=cia.curso_intensivo_id WHERE cia.horario_id=h.id AND ci.sede_id=:sc AND ci.estado IN ('PROGRAMADO','EN_CURSO') AND :f BETWEEN ci.fecha_inicio AND ci.fecha_fin)) ORDER BY h.hora_inicio";
 $st=$pdo->prepare($sql);$st->execute([':s'=>$sedeId,':sa'=>$sedeId,':sc'=>$sedeId,':f'=>$fecha]);$horarios=$st->fetchAll();$n=0;
 foreach($horarios as $h){$bloque=((int)substr((string)$h['hora_inicio'],0,2)<12)?'AM':'PM';$q=$pdo->prepare("INSERT IGNORE INTO sesiones(fecha,bloque,horario_id,created_by) VALUES(:f,:b,:h,:u)");$q->execute([':f'=>$fecha,':b'=>$bloque,':h'=>$h['id'],':u'=>$uid]);$n+=$q->rowCount();}
 return $n;
}
function alumnosSesion(PDO $pdo,array $s,string $fecha,string $sedeId):array{
 if(!$s['horario_id'])return [];
 $q=$pdo->prepare("SELECT a.id,a.nombre,a.estado_administrativo,p.sesiones_semana,aa.estado asistencia_estado,aa.observacion,EXISTS(SELECT 1 FROM curso_intensivo_alumnos cia JOIN cursos_intensivos ci ON ci.id=cia.curso_intensivo_id WHERE cia.alumno_id=a.id AND cia.horario_id=:h1 AND ci.sede_id=:sc1 AND ci.estado IN ('PROGRAMADO','EN_CURSO') AND :f1 BETWEEN ci.fecha_inicio AND ci.fecha_fin) intensivo_activo,(SELECT cia.curso_intensivo_id FROM curso_intensivo_alumnos cia JOIN cursos_intensivos ci ON ci.id=cia.curso_intensivo_id WHERE cia.alumno_id=a.id AND cia.horario_id=:h2 AND ci.sede_id=:sc2 AND ci.estado IN ('PROGRAMADO','EN_CURSO') AND :f2 BETWEEN ci.fecha_inicio AND ci.fecha_fin LIMIT 1) curso_intensivo_id FROM alumnos a LEFT JOIN planes p ON p.id=a.plan_actual_id AND p.sede_id=a.sede_id LEFT JOIN asistencias aa ON aa.sesion_id=:sid AND aa.alumno_id=a.id WHERE a.sede_id=:sa AND ((a.horario_preferido_id=:h3 AND a.estado_administrativo IN ('ACTIVO','PENDIENTE')) OR EXISTS(SELECT 1 FROM curso_intensivo_alumnos cia2 JOIN cursos_intensivos ci2 ON ci2.id=cia2.curso_intensivo_id WHERE cia2.alumno_id=a.id AND cia2.horario_id=:h4 AND ci2.sede_id=:sc3 AND ci2.estado IN ('PROGRAMADO','EN_CURSO') AND :f5 BETWEEN ci2.fecha_inicio AND ci2.fecha_fin)) ORDER BY a.nombre");
 $q->execute([':h1'=>$s['horario_id'],':sc1'=>$sedeId,':f1'=>$fecha,':h2'=>$s['horario_id'],':sc2'=>$sedeId,':f2'=>$fecha,':sid'=>$s['id'],':sa'=>$sedeId,':h3'=>$s['horario_id'],':h4'=>$s['horario_id'],':sc3'=>$sedeId,':f5'=>$fecha]);$rows=$q->fetchAll();$dia=new DateTimeImmutable($fecha);foreach($rows as &$a){$derecho=regla_derecho_clase($pdo,(string)$a['id'],$sedeId,(string)$s['horario_id'],$dia);$a['puede_tomar_clase']=$derecho['puede'];$a['mensualidad_estado']=($derecho['tipo']==='REGULAR'&&!empty($derecho['mensualidad_cubierta']))?'PAGADA':null;$a['motivo_bloqueo']=$derecho['motivo'];}unset($a);return $rows;
}
function sincronizarReposicion(PDO $pdo,string $sid,string $aid,string $estado,string $uid):array{
 $st=$pdo->prepare("SELECT s.fecha,a.plan_actual_id,p.sesiones_semana,(SELECT cia.id FROM curso_intensivo_alumnos cia JOIN cursos_intensivos ci ON ci.id=cia.curso_intensivo_id WHERE cia.alumno_id=a.id AND cia.horario_id=s.horario_id AND ci.sede_id=a.sede_id AND ci.estado IN ('PROGRAMADO','EN_CURSO') AND s.fecha BETWEEN ci.fecha_inicio AND ci.fecha_fin LIMIT 1) cia_id,(SELECT cia.curso_intensivo_id FROM curso_intensivo_alumnos cia JOIN cursos_intensivos ci ON ci.id=cia.curso_intensivo_id WHERE cia.alumno_id=a.id AND cia.horario_id=s.horario_id AND ci.sede_id=a.sede_id AND ci.estado IN ('PROGRAMADO','EN_CURSO') AND s.fecha BETWEEN ci.fecha_inicio AND ci.fecha_fin LIMIT 1) curso_id FROM sesiones s JOIN horarios hs ON hs.id=s.horario_id JOIN alumnos a ON a.id=:a AND a.sede_id=hs.sede_id LEFT JOIN planes p ON p.id=a.plan_actual_id AND p.sede_id=a.sede_id WHERE s.id=:s LIMIT 1");$st->execute([':a'=>$aid,':s'=>$sid]);$x=$st->fetch();if(!$x)return ['generada'=>false];
 $st=$pdo->prepare("SELECT id FROM asistencias WHERE sesion_id=:s AND alumno_id=:a LIMIT 1");$st->execute([':s'=>$sid,':a'=>$aid]);$asistencia=(string)$st->fetchColumn();
 if($x['cia_id']){if($estado==='AUSENTE_JUSTIFICADA'){$st=$pdo->prepare("SELECT reposiciones_justificadas FROM curso_intensivo_alumnos WHERE id=:id LIMIT 1 FOR UPDATE");$st->execute([':id'=>$x['cia_id']]);$creditos=(int)$st->fetchColumn();if($creditos>=5)return ['generada'=>false,'tipo'=>'INTENSIVO','limite'=>5,'motivo'=>'Ya alcanzó 5 reposiciones justificadas'];$id=(string)$pdo->query("SELECT UUID()")->fetchColumn();$st=$pdo->prepare("INSERT IGNORE INTO ausencias(id,intensivo_id,alumno_id,fecha,motivo) VALUES(:id,:c,:a,:f,:m)");$st->execute([':id'=>$id,':c'=>$x['curso_id'],':a'=>$aid,':f'=>$x['fecha'],':m'=>'Ausencia justificada en sesión']);$n=$st->rowCount();if($n){$st=$pdo->prepare("UPDATE curso_intensivo_alumnos SET reposiciones_justificadas=reposiciones_justificadas+1 WHERE id=:id AND reposiciones_justificadas<5");$st->execute([':id'=>$x['cia_id']]);}return ['generada'=>$n>0,'tipo'=>'INTENSIVO','limite'=>5];}$st=$pdo->prepare("DELETE FROM ausencias WHERE intensivo_id=:c AND alumno_id=:a AND fecha=:f AND motivo='Ausencia justificada en sesión'");$st->execute([':c'=>$x['curso_id'],':a'=>$aid,':f'=>$x['fecha']]);if($st->rowCount()){$st=$pdo->prepare("UPDATE curso_intensivo_alumnos SET reposiciones_justificadas=GREATEST(reposiciones_justificadas-1,0) WHERE id=:id");$st->execute([':id'=>$x['cia_id']]);}return ['generada'=>false,'tipo'=>'INTENSIVO'];}
 if(!$asistencia)return ['generada'=>false];if($estado!=='AUSENTE_JUSTIFICADA'){$st=$pdo->prepare("UPDATE reposiciones_regulares SET estado='CANCELADA' WHERE ausencia_asistencia_id=:aus AND estado='DISPONIBLE'");$st->execute([':aus'=>$asistencia]);return ['generada'=>false,'tipo'=>'REGULAR'];}if((int)$x['sesiones_semana']!==3)return ['generada'=>false,'motivo'=>'El plan no genera reposiciones'];$st=$pdo->prepare("SELECT id,estado FROM reposiciones_regulares WHERE ausencia_asistencia_id=:aus LIMIT 1");$st->execute([':aus'=>$asistencia]);$exist=$st->fetch();if($exist&&$exist['estado']==='DISPONIBLE')return ['generada'=>false,'tipo'=>'REGULAR','ya_existia'=>true];$st=$pdo->prepare("SELECT COUNT(*) FROM reposiciones_regulares rr JOIN asistencias aa ON aa.id=rr.ausencia_asistencia_id JOIN sesiones s ON s.id=aa.sesion_id WHERE rr.alumno_id=:a AND YEAR(s.fecha)=YEAR(:f1) AND MONTH(s.fecha)=MONTH(:f2) AND rr.estado IN ('DISPONIBLE','USADA')");$st->execute([':a'=>$aid,':f1'=>$x['fecha'],':f2'=>$x['fecha']]);if((int)$st->fetchColumn()>=2)return ['generada'=>false,'motivo'=>'Ya alcanzó 2 reposiciones del mes'];if($exist){$st=$pdo->prepare("UPDATE reposiciones_regulares SET estado='DISPONIBLE',sesion_reposicion_id=NULL,used_at=NULL WHERE id=:id");$st->execute([':id'=>$exist['id']]);return ['generada'=>true,'tipo'=>'REGULAR','limite'=>2];}$id=(string)$pdo->query("SELECT UUID()")->fetchColumn();$st=$pdo->prepare("INSERT INTO reposiciones_regulares(id,alumno_id,ausencia_asistencia_id,created_by) VALUES(:id,:a,:aus,:u)");$st->execute([':id'=>$id,':a'=>$aid,':aus'=>$asistencia,':u'=>$uid]);return ['generada'=>true,'tipo'=>'REGULAR','limite'=>2];
}
try{
 $method=$_SERVER['REQUEST_METHOD']??'GET';
 if($method==='GET'){$me=auth_require(['ADMIN','VERIFICADOR']);$clave=auth_resolve_sede_clave((string)($_GET['sede']??'MONTEVERDE'));$sedeId=siteId($pdo,$clave);$fecha=(string)($_GET['fecha']??date('Y-m-d'));fechaLaborable($fecha);$uid=(string)$me['id'];$creadas=($me['rol']==='ADMIN')?generarSesiones($pdo,$fecha,$uid,$sedeId):0;$stmt=$pdo->prepare("SELECT s.id,s.fecha,s.bloque,s.horario_id,s.estado,s.cerrada,s.motivo_cancelacion,h.hora_inicio,h.hora_fin FROM sesiones s JOIN horarios h ON h.id=s.horario_id WHERE s.fecha=:f AND h.sede_id=:site ORDER BY h.hora_inicio,s.bloque");$stmt->execute([':f'=>$fecha,':site'=>$sedeId]);$sesiones=$stmt->fetchAll();foreach($sesiones as &$s)$s['alumnos']=alumnosSesion($pdo,$s,$fecha,$sedeId);unset($s);out(['ok'=>true,'fecha'=>$fecha,'sede'=>$clave,'sesiones_creadas'=>$creadas,'sesiones'=>$sesiones]);}
 $me=auth_require(['ADMIN']);if($method!=='POST')out(['ok'=>false,'error'=>'Método no permitido'],405);$in=json_decode(file_get_contents('php://input'),true);if(!is_array($in))out(['ok'=>false,'error'=>'JSON inválido'],400);$clave=auth_resolve_sede_clave((string)($in['sede']??'MONTEVERDE'));$sedeId=siteId($pdo,$clave);$uid=(string)$me['id'];$accion=strtoupper((string)($in['accion']??''));
 if($accion==='GENERAR'){$fecha=(string)($in['fecha']??date('Y-m-d'));fechaLaborable($fecha);out(['ok'=>true,'creadas'=>generarSesiones($pdo,$fecha,$uid,$sedeId)]);}
 if($accion==='ASISTENCIA'){$sid=(string)($in['sesion_id']??'');$aid=(string)($in['alumno_id']??'');$estado=(string)($in['estado']??'');$observacion=trim((string)($in['observacion']??''));if(!in_array($estado,['PRESENTE','AUSENTE_JUSTIFICADA','AUSENTE_NO_JUSTIFICADA'],true))out(['ok'=>false,'error'=>'Estado inválido'],422);if(mb_strlen($observacion)>500)out(['ok'=>false,'error'=>'La observación no puede exceder 500 caracteres'],422);$pdo->beginTransaction();$scope=$pdo->prepare("SELECT s.fecha,s.horario_id FROM sesiones s JOIN horarios h ON h.id=s.horario_id JOIN alumnos a ON a.id=:a WHERE s.id=:ss AND h.sede_id=:sh AND a.sede_id=:sa AND s.cerrada=0 AND s.estado<>'CANCELADA' LIMIT 1 FOR UPDATE");$scope->execute([':a'=>$aid,':ss'=>$sid,':sh'=>$sedeId,':sa'=>$sedeId]);$sesion=$scope->fetch();if(!$sesion){$pdo->rollBack();out(['ok'=>false,'error'=>'La sesión no está abierta o no pertenece a la sede seleccionada'],409);}$derecho=regla_derecho_clase($pdo,$aid,$sedeId,(string)$sesion['horario_id'],new DateTimeImmutable((string)$sesion['fecha']));if(!$derecho['puede']){$pdo->rollBack();out(['ok'=>false,'error'=>$derecho['motivo']?:'El alumno no tiene derecho a tomar esta clase'],422);}$st=$pdo->prepare("INSERT INTO asistencias(sesion_id,alumno_id,estado,observacion,created_by) VALUES(:s,:a,:e,:o,:u) ON DUPLICATE KEY UPDATE estado=VALUES(estado),observacion=VALUES(observacion),updated_at=NOW()");$st->execute([':s'=>$sid,':a'=>$aid,':e'=>$estado,':o'=>$observacion!==''?$observacion:null,':u'=>$uid]);$repo=sincronizarReposicion($pdo,$sid,$aid,$estado,$uid);$pdo->commit();out(['ok'=>true,'reposicion'=>$repo]);}
 if($accion==='CERRAR'){$sid=trim((string)($in['sesion_id']??''));if($sid==='')out(['ok'=>false,'error'=>'La sesión es obligatoria'],422);$st=$pdo->prepare("UPDATE sesiones s JOIN horarios h ON h.id=s.horario_id SET s.estado='REALIZADA',s.cerrada=1,s.fecha_cierre=NOW(),s.cerrada_por=:u WHERE s.id=:ss AND h.sede_id=:site AND s.cerrada=0 AND s.estado<>'CANCELADA'");$st->execute([':u'=>$uid,':ss'=>$sid,':site'=>$sedeId]);if($st->rowCount()===0)out(['ok'=>false,'error'=>'La sesión no existe, ya está cerrada o fue cancelada'],409);out(['ok'=>true]);}
 out(['ok'=>false,'error'=>'Acción inválida'],422);
}catch(Throwable $e){if(isset($pdo)&&$pdo instanceof PDO&&$pdo->inTransaction())$pdo->rollBack();error_log('[sesiones] '.$e->getMessage());out(['ok'=>false,'error'=>'No se pudo procesar la sesión'],500);}
