<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
$config=require __DIR__.'/../config/database.php';$pdo=new PDO("mysql:host={$config['host']};dbname={$config['dbname']};charset={$config['charset']}",$config['user'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
$id=trim((string)($_GET['alumno_id']??''));if($id===''){http_response_code(422);echo json_encode(['ok'=>false,'error'=>'alumno_id obligatorio']);exit;}$items=[];
$push=function(string $fecha,string $tipo,string $titulo,string $detalle='')use(&$items){$items[]=['fecha'=>$fecha,'tipo'=>$tipo,'titulo'=>$titulo,'detalle'=>$detalle];};
$st=$pdo->prepare("SELECT fecha,tipo,importe,metodo,estado,folio,observacion FROM pagos WHERE alumno_id=:a ORDER BY fecha");$st->execute([':a'=>$id]);foreach($st as $r)$push($r['fecha'],'PAGO',$r['tipo'].' · $'.number_format((float)$r['importe'],0),'Folio '.$r['folio'].' · '.$r['metodo'].($r['estado']!=='VALIDO'?' · '.$r['estado']:'').($r['observacion']?' · '.$r['observacion']:''));
$st=$pdo->prepare("SELECT ci.fecha_inicio,ci.fecha_fin,ci.estado,cia.continua_regular,cia.observacion_continuidad FROM curso_intensivo_alumnos cia JOIN cursos_intensivos ci ON ci.id=cia.curso_intensivo_id WHERE cia.alumno_id=:a ORDER BY ci.fecha_inicio");$st->execute([':a'=>$id]);foreach($st as $r)$push($r['fecha_inicio'].' 00:00:00','INTENSIVO','Curso intensivo','Del '.date('d/m/Y',strtotime($r['fecha_inicio'])).' al '.date('d/m/Y',strtotime($r['fecha_fin'])).' · '.$r['estado'].($r['continua_regular']?' · Continuó a regular':'').($r['observacion_continuidad']?' · '.$r['observacion_continuidad']:''));
$st=$pdo->prepare("SELECT s.fecha,a.estado,a.observacion FROM asistencias a JOIN sesiones s ON s.id=a.sesion_id WHERE a.alumno_id=:x ORDER BY s.fecha");$st->execute([':x'=>$id]);foreach($st as $r)$push($r['fecha'].' 12:00:00','ASISTENCIA',$r['estado'],$r['observacion']??'');
$st=$pdo->prepare("SELECT fecha_desde,fecha_hasta,motivo,estado FROM avisos_ausencia WHERE alumno_id=:a ORDER BY fecha_desde");$st->execute([':a'=>$id]);foreach($st as $r)$push($r['fecha_desde'].' 00:00:00','AUSENCIA','Aviso de ausencia · '.$r['estado'],'Hasta '.date('d/m/Y',strtotime($r['fecha_hasta'])).' · '.$r['motivo']);
$st=$pdo->prepare("SELECT fecha_hora,tipo,descripcion FROM historial WHERE alumno_id=:a ORDER BY fecha_hora");$st->execute([':a'=>$id]);foreach($st as $r)$push($r['fecha_hora'],'HISTORIAL',$r['tipo'],$r['descripcion']);
usort($items,fn($a,$b)=>strcmp($b['fecha'],$a['fecha']));echo json_encode(['ok'=>true,'items'=>$items],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
